export interface QuestionData {
  points: number;
  question: string;
  answer: string;
}

export const POINT_VALUES = [200, 400, 600, 800, 1000, 1200];

export const ALL_CATEGORIES = [
  "Science", "History", "Geography", "Sports",
  "Movies & TV", "Music", "Technology", "Literature",
  "Art", "Food & Drink", "Nature", "Politics",
];

// Difficulty scale:
// 200  — Everyone knows this (trivial / very easy)
// 400  — Most adults know this (easy / common knowledge)
// 600  — Requires some education or interest in the subject (medium)
// 800  — Requires specific knowledge; many people would guess (medium-hard)
// 1000 — Hard; requires deep interest or study
// 1200 — Expert level; most people do not know this

export const MOCK_QUESTIONS: Record<string, QuestionData[]> = {

  // ─────────────────────────────────────────────────────────────── SCIENCE ──────
  Science: [
    // 200 — Very Easy (9)
    { points: 200, question: "How many planets are in our solar system?", answer: "8" },
    { points: 200, question: "What is the boiling point of water in Celsius?", answer: "100°C" },
    { points: 200, question: "What is the chemical formula for water?", answer: "H₂O" },
    { points: 200, question: "What organ pumps blood through the human body?", answer: "The heart" },
    { points: 200, question: "What force keeps us on the ground?", answer: "Gravity" },
    { points: 200, question: "What is the closest star to Earth?", answer: "The Sun" },
    { points: 200, question: "What gas do plants absorb to make their food?", answer: "Carbon dioxide (CO₂)" },
    { points: 200, question: "What type of animal is a whale?", answer: "A mammal" },
    { points: 200, question: "What do we call the center of an atom?", answer: "The nucleus" },
    // 400 — Easy (9)
    { points: 400, question: "What is the chemical symbol for gold?", answer: "Au" },
    { points: 400, question: "What planet is known as the Red Planet?", answer: "Mars" },
    { points: 400, question: "What is the largest organ of the human body?", answer: "The skin" },
    { points: 400, question: "What gas makes up approximately 78% of Earth's atmosphere?", answer: "Nitrogen" },
    { points: 400, question: "How many chambers does the human heart have?", answer: "4" },
    { points: 400, question: "What is the powerhouse of the cell?", answer: "The mitochondria" },
    { points: 400, question: "What is the approximate speed of light?", answer: "~300,000 km/s" },
    { points: 400, question: "What element is needed for combustion (fire) to occur?", answer: "Oxygen" },
    { points: 400, question: "What is the process by which plants make food using sunlight called?", answer: "Photosynthesis" },
    // 600 — Medium (8)
    { points: 600, question: "Which organ in the human body produces insulin?", answer: "The pancreas" },
    { points: 600, question: "What is the process called when a liquid turns into a gas?", answer: "Evaporation (vaporization)" },
    { points: 600, question: "What does Newton's Third Law of Motion state?", answer: "For every action there is an equal and opposite reaction" },
    { points: 600, question: "What element has the chemical symbol Fe?", answer: "Iron" },
    { points: 600, question: "What type of rock is formed when molten lava cools and solidifies?", answer: "Igneous rock" },
    { points: 600, question: "How many chromosomes does a typical human cell contain?", answer: "46" },
    { points: 600, question: "What is the scientific name for table salt?", answer: "Sodium chloride (NaCl)" },
    { points: 600, question: "What is the pH value of a neutral solution?", answer: "7" },
    // 800 — Medium-Hard (8)
    { points: 800, question: "What is the name of the process by which a solid turns directly into a gas without becoming liquid?", answer: "Sublimation" },
    { points: 800, question: "What is the SI unit of electrical resistance?", answer: "Ohm (Ω)" },
    { points: 800, question: "What particle in the nucleus of an atom has no electrical charge?", answer: "Neutron" },
    { points: 800, question: "What is the name of the process cells use to break down glucose and produce energy?", answer: "Cellular respiration" },
    { points: 800, question: "What phenomenon describes the apparent change in frequency of a wave as its source moves toward or away from an observer?", answer: "The Doppler effect" },
    { points: 800, question: "What is Avogadro's number?", answer: "6.022 × 10²³" },
    { points: 800, question: "What is the study of fossils called?", answer: "Paleontology" },
    { points: 800, question: "What is the name for an atom that has gained or lost electrons?", answer: "An ion" },
    // 1000 — Hard (8)
    { points: 1000, question: "What is the atomic number of carbon?", answer: "6" },
    { points: 1000, question: "What is the Heisenberg Uncertainty Principle?", answer: "You cannot simultaneously know both the exact position and exact momentum of a particle" },
    { points: 1000, question: "What phenomenon causes a straw to appear bent in a glass of water?", answer: "Refraction" },
    { points: 1000, question: "What protein carries oxygen in red blood cells?", answer: "Hemoglobin" },
    { points: 1000, question: "In DNA, which base pairs with adenine?", answer: "Thymine" },
    { points: 1000, question: "What is the name of the boundary between Earth's mantle and outer core?", answer: "The Gutenberg discontinuity" },
    { points: 1000, question: "What does the Second Law of Thermodynamics state?", answer: "The entropy (disorder) of a closed system tends to increase over time" },
    { points: 1000, question: "Which element has the highest melting point of all known elements?", answer: "Tungsten (W), at approximately 3,422°C" },
    // 1200 — Expert (8)
    { points: 1200, question: "What is the half-life of Carbon-14, used in radiocarbon dating?", answer: "Approximately 5,730 years" },
    { points: 1200, question: "What quantum mechanical effect allows particles to pass through energy barriers they classically could not?", answer: "Quantum tunneling" },
    { points: 1200, question: "What is the name of the enzyme that unwinds the DNA double helix during replication?", answer: "Helicase" },
    { points: 1200, question: "What is Planck's constant (approximate value)?", answer: "6.626 × 10⁻³⁴ joule-seconds" },
    { points: 1200, question: "What physical law states that the entropy of a perfect crystal at absolute zero is exactly zero?", answer: "The Third Law of Thermodynamics" },
    { points: 1200, question: "What is the name of the point inside a black hole where density becomes infinite and the laws of physics break down?", answer: "The singularity" },
    { points: 1200, question: "What is the difference between a sigma bond and a pi bond?", answer: "Sigma bonds form by head-on orbital overlap; pi bonds form by side-to-side orbital overlap" },
    { points: 1200, question: "What is the P vs NP problem in mathematics and computer science?", answer: "The unsolved question of whether every problem whose solution can be quickly verified can also be quickly solved" },
  ],

  // ─────────────────────────────────────────────────────────────── HISTORY ──────
  History: [
    // 200 — Very Easy (9)
    { points: 200, question: "Who was the first President of the United States?", answer: "George Washington" },
    { points: 200, question: "In which century did World War II take place?", answer: "The 20th century (1939–1945)" },
    { points: 200, question: "Which ancient civilization built the Pyramids of Giza?", answer: "The ancient Egyptians" },
    { points: 200, question: "Who was the primary author of the Declaration of Independence?", answer: "Thomas Jefferson" },
    { points: 200, question: "What war was fought between the North and South of the United States?", answer: "The American Civil War" },
    { points: 200, question: "Which empire was ruled by Julius Caesar?", answer: "The Roman Empire" },
    { points: 200, question: "What country did Christopher Columbus sail from when he discovered the Americas?", answer: "Spain" },
    { points: 200, question: "In which continent is the country of Egypt located?", answer: "Africa" },
    { points: 200, question: "What wall separated East and West Germany during the Cold War?", answer: "The Berlin Wall" },
    // 400 — Easy (9)
    { points: 400, question: "In what year did World War I begin?", answer: "1914" },
    { points: 400, question: "Who was the first man to walk on the Moon?", answer: "Neil Armstrong" },
    { points: 400, question: "In what year did the Berlin Wall fall?", answer: "1989" },
    { points: 400, question: "Who was the leader of Germany during World War II?", answer: "Adolf Hitler" },
    { points: 400, question: "What was the name of the ship that sank on its maiden voyage in 1912?", answer: "The Titanic" },
    { points: 400, question: "Who was the first female Prime Minister of the United Kingdom?", answer: "Margaret Thatcher" },
    { points: 400, question: "What ancient document signed in 1215 limited the power of the English king?", answer: "The Magna Carta" },
    { points: 400, question: "In what city were the first modern Olympic Games (1896) held?", answer: "Athens, Greece" },
    { points: 400, question: "In what year did India gain independence from British rule?", answer: "1947" },
    // 600 — Medium (8)
    { points: 600, question: "What was the name of the first artificial satellite launched into space?", answer: "Sputnik 1" },
    { points: 600, question: "Who was the leader of the Soviet Union during the Cuban Missile Crisis?", answer: "Nikita Khrushchev" },
    { points: 600, question: "In what year was the United Nations founded?", answer: "1945" },
    { points: 600, question: "What ancient trade route connected China to the Mediterranean world?", answer: "The Silk Road" },
    { points: 600, question: "What event in 1929 triggered the Great Depression?", answer: "The Wall Street Crash (Black Tuesday)" },
    { points: 600, question: "Who led the Cuban Revolution in 1959?", answer: "Fidel Castro" },
    { points: 600, question: "Which Egyptian pharaoh is most associated with the construction of the Great Pyramid of Giza?", answer: "Khufu (Cheops)" },
    { points: 600, question: "In what year was the French Revolution?", answer: "1789" },
    // 800 — Medium-Hard (8)
    { points: 800, question: "In what year did the Byzantine Empire fall to the Ottoman Turks?", answer: "1453" },
    { points: 800, question: "What was the name of the treaty that officially ended World War I?", answer: "The Treaty of Versailles" },
    { points: 800, question: "What was the code name for the Allied D-Day invasion of Normandy in 1944?", answer: "Operation Overlord" },
    { points: 800, question: "Which empire was the largest contiguous land empire in history?", answer: "The Mongol Empire" },
    { points: 800, question: "Who was the first Roman Emperor?", answer: "Augustus (Octavian)" },
    { points: 800, question: "What was the name of the Soviet nuclear reactor that exploded in 1986?", answer: "Chernobyl" },
    { points: 800, question: "In what year did the apartheid regime officially end in South Africa?", answer: "1994" },
    { points: 800, question: "What battle in 1066 resulted in the Norman conquest of England?", answer: "The Battle of Hastings" },
    // 1000 — Hard (8)
    { points: 1000, question: "What war was fought between Athens and Sparta from 431–404 BC?", answer: "The Peloponnesian War" },
    { points: 1000, question: "Who was the first Secretary-General of the United Nations?", answer: "Trygve Lie (Norway)" },
    { points: 1000, question: "What was the name of the pact signed between Nazi Germany and the Soviet Union in 1939?", answer: "The Molotov-Ribbentrop Pact" },
    { points: 1000, question: "Who was the Ottoman Sultan who conquered Constantinople in 1453?", answer: "Mehmed II (Mehmed the Conqueror)" },
    { points: 1000, question: "What empire was founded by Cyrus the Great around 550 BC?", answer: "The Achaemenid (Persian) Empire" },
    { points: 1000, question: "In what year did the Russian Revolution overthrow Tsar Nicholas II?", answer: "1917" },
    { points: 1000, question: "What was the name of the ship that carried the Pilgrims to Plymouth, Massachusetts in 1620?", answer: "The Mayflower" },
    { points: 1000, question: "What treaty ended the Thirty Years' War in 1648?", answer: "The Peace of Westphalia" },
    // 1200 — Expert (8)
    { points: 1200, question: "What was the name of the ancient Egyptian chancellor who built the Step Pyramid at Saqqara?", answer: "Imhotep" },
    { points: 1200, question: "In what year did the Ming Dynasty fall and the Qing Dynasty begin in China?", answer: "1644" },
    { points: 1200, question: "Who was the Carthaginian general who famously crossed the Alps with war elephants to attack Rome?", answer: "Hannibal Barca" },
    { points: 1200, question: "Which Roman Emperor converted the empire to Christianity and issued the Edict of Milan?", answer: "Constantine the Great" },
    { points: 1200, question: "What was the name of Lenin's economic policy introduced in 1921 that allowed limited private enterprise in the Soviet Union?", answer: "The New Economic Policy (NEP)" },
    { points: 1200, question: "In what year was the Battle of Marathon fought between Athens and Persia?", answer: "490 BC" },
    { points: 1200, question: "What was the name of the interwar international organization that preceded the United Nations?", answer: "The League of Nations" },
    { points: 1200, question: "Who led the Mongol conquest of China and founded the Yuan Dynasty?", answer: "Kublai Khan" },
  ],

  // ──────────────────────────────────────────────────────────── GEOGRAPHY ───────
  Geography: [
    // 200 — Very Easy (9)
    { points: 200, question: "What is the capital city of France?", answer: "Paris" },
    { points: 200, question: "What is the largest ocean in the world?", answer: "The Pacific Ocean" },
    { points: 200, question: "On which continent is the Amazon rainforest located?", answer: "South America" },
    { points: 200, question: "What is the capital of the United Kingdom?", answer: "London" },
    { points: 200, question: "How many continents are there on Earth?", answer: "7" },
    { points: 200, question: "What is the tallest mountain in the world?", answer: "Mount Everest" },
    { points: 200, question: "What is the longest river in the world?", answer: "The Nile" },
    { points: 200, question: "What is the smallest continent by area?", answer: "Australia" },
    { points: 200, question: "What is the capital city of Japan?", answer: "Tokyo" },
    // 400 — Easy (9)
    { points: 400, question: "What is the largest continent by area?", answer: "Asia" },
    { points: 400, question: "What country has the most natural lakes in the world?", answer: "Canada" },
    { points: 400, question: "What two continents does the country of Russia span?", answer: "Europe and Asia" },
    { points: 400, question: "What is the capital city of Australia?", answer: "Canberra" },
    { points: 400, question: "What ocean lies between Europe and North America?", answer: "The Atlantic Ocean" },
    { points: 400, question: "What is the name of the longest mountain range in the world?", answer: "The Andes" },
    { points: 400, question: "What country is the Nile River most associated with?", answer: "Egypt" },
    { points: 400, question: "What is the capital of Brazil?", answer: "Brasília" },
    { points: 400, question: "On which continent is the Sahara Desert located?", answer: "Africa" },
    // 600 — Medium (8)
    { points: 600, question: "What is the name of the world's largest hot desert?", answer: "The Sahara Desert" },
    { points: 600, question: "What is the capital city of Kazakhstan?", answer: "Astana (formerly Nur-Sultan)" },
    { points: 600, question: "What country shares the longest land border with the United States?", answer: "Canada" },
    { points: 600, question: "What is the name of the sea between Europe and Africa?", answer: "The Mediterranean Sea" },
    { points: 600, question: "What is the approximate area of Russia in square kilometres?", answer: "Approximately 17.1 million km²" },
    { points: 600, question: "What is the name of a narrow body of water connecting two larger bodies of water?", answer: "A strait" },
    { points: 600, question: "Which country has the largest population in the world (as of 2024)?", answer: "India" },
    { points: 600, question: "On which continent is the country of Argentina located?", answer: "South America" },
    // 800 — Medium-Hard (8)
    { points: 800, question: "Through how many countries does the Danube River flow?", answer: "10 countries" },
    { points: 800, question: "What is the deepest lake in the world?", answer: "Lake Baikal (Russia)" },
    { points: 800, question: "What is the name of the geographic boundary between Europe and Asia?", answer: "The Ural Mountains (and Ural River)" },
    { points: 800, question: "Which country has the most time zones (including overseas territories)?", answer: "France (12 time zones)" },
    { points: 800, question: "What is the name of the world's largest island (excluding continents)?", answer: "Greenland" },
    { points: 800, question: "In which country is the Atacama Desert, the driest non-polar desert, located?", answer: "Chile" },
    { points: 800, question: "What is the name of the only sea with no land boundaries?", answer: "The Sargasso Sea" },
    { points: 800, question: "What is the geographic term for a strip of land connecting two larger landmasses?", answer: "An isthmus" },
    // 1000 — Hard (8)
    { points: 1000, question: "What is the capital city of Myanmar (Burma)?", answer: "Naypyidaw" },
    { points: 1000, question: "What is the name of the geographic phenomenon where two tectonic plates move away from each other?", answer: "A divergent plate boundary" },
    { points: 1000, question: "What is the approximate length of the Amazon River in kilometres?", answer: "Approximately 6,400 km" },
    { points: 1000, question: "Which country is completely surrounded by just one other country?", answer: "Lesotho (surrounded by South Africa)" },
    { points: 1000, question: "What is the Coriolis effect in weather systems?", answer: "The deflection of wind and ocean currents caused by Earth's rotation — to the right in the Northern Hemisphere and left in the Southern" },
    { points: 1000, question: "What is the name of the world's highest navigable lake?", answer: "Lake Titicaca (Bolivia/Peru)" },
    { points: 1000, question: "What is the name of the deep ocean current system driven by temperature and salinity differences?", answer: "Thermohaline circulation (the ocean conveyor belt)" },
    { points: 1000, question: "What is the geographic term for the point where three country borders meet?", answer: "A tripoint (trijunction)" },
    // 1200 — Expert (8)
    { points: 1200, question: "What is the approximate elevation of the Dead Sea below sea level?", answer: "Approximately 430 metres below sea level" },
    { points: 1200, question: "What is the capital of the Federated States of Micronesia?", answer: "Palikir" },
    { points: 1200, question: "What is the name of the subsea mountain range that runs the length of the Atlantic Ocean?", answer: "The Mid-Atlantic Ridge" },
    { points: 1200, question: "What country is Socotra Island — famous for its unique biodiversity — part of?", answer: "Yemen" },
    { points: 1200, question: "What is the geographic process by which rivers deposit sediment to form fertile floodplains?", answer: "Alluviation (alluvial deposition)" },
    { points: 1200, question: "What is the Fjord formation in Norway caused by geologically?", answer: "Glacially carved valleys (glacial troughs) that were subsequently flooded by the sea" },
    { points: 1200, question: "What is the name of the Chinese region through which three great rivers — the Mekong, Salween, and Yangtze — run in deep parallel gorges?", answer: "The Three Parallel Rivers region (Yunnan, China)" },
    { points: 1200, question: "What is the approximate depth of the Mariana Trench's Challenger Deep in kilometres?", answer: "Approximately 11 km (10,994 metres)" },
  ],

  // ──────────────────────────────────────────────────────────────── SPORTS ──────
  Sports: [
    // 200 — Very Easy (9)
    { points: 200, question: "How many players are on a basketball team on the court at one time?", answer: "5 players" },
    { points: 200, question: "In which sport do players use a racket and a ball on a grass or clay court?", answer: "Tennis" },
    { points: 200, question: "How many players are on a soccer (football) team on the field?", answer: "11 players" },
    { points: 200, question: "How many innings are in a standard baseball game?", answer: "9 innings" },
    { points: 200, question: "In which sport would you perform a slam dunk?", answer: "Basketball" },
    { points: 200, question: "What sport uses a puck instead of a ball?", answer: "Ice hockey" },
    { points: 200, question: "How many players are on each side of the net in volleyball?", answer: "6 players" },
    { points: 200, question: "What is the objective of the game of golf?", answer: "To hit a ball into a series of holes in as few strokes as possible" },
    { points: 200, question: "How many gold medals can an athlete win at a single Olympic Games event?", answer: "1 gold medal per event" },
    // 400 — Easy (9)
    { points: 400, question: "In which country was the first FIFA World Cup held?", answer: "Uruguay (1930)" },
    { points: 400, question: "How many holes are played in a standard round of golf?", answer: "18 holes" },
    { points: 400, question: "In what year were the first modern Olympic Games held?", answer: "1896 (Athens, Greece)" },
    { points: 400, question: "How many points is a touchdown worth in American football?", answer: "6 points" },
    { points: 400, question: "What sport is played at Wimbledon?", answer: "Tennis" },
    { points: 400, question: "How many players are on each side in a rugby union match?", answer: "15 players" },
    { points: 400, question: "What does 'LBW' stand for in cricket?", answer: "Leg Before Wicket" },
    { points: 400, question: "How many minutes does a standard round of boxing last?", answer: "3 minutes" },
    { points: 400, question: "Which country has won the most FIFA World Cup titles?", answer: "Brazil (5 times)" },
    // 600 — Medium (8)
    { points: 600, question: "What is the maximum number of sets in a men's Grand Slam tennis singles match?", answer: "5 sets" },
    { points: 600, question: "In golf, what is the term for scoring one stroke under par on a hole?", answer: "Birdie" },
    { points: 600, question: "How many events make up the decathlon?", answer: "10 events" },
    { points: 600, question: "What is the distance of a marathon in kilometres?", answer: "42.195 km" },
    { points: 600, question: "In which city were the 2016 Summer Olympics held?", answer: "Rio de Janeiro, Brazil" },
    { points: 600, question: "In Olympic weightlifting, what are the two lifts performed?", answer: "Snatch and Clean-and-Jerk" },
    { points: 600, question: "What is the name of the international governing body of football (soccer)?", answer: "FIFA" },
    { points: 600, question: "What is the highest possible break in snooker?", answer: "147" },
    // 800 — Medium-Hard (8)
    { points: 800, question: "What is the official weight of the men's Olympic shot put in kilograms?", answer: "7.26 kg" },
    { points: 800, question: "What is the term for a perfect game in ten-pin bowling?", answer: "A perfect game — 300 points (12 consecutive strikes)" },
    { points: 800, question: "In swimming, what is the butterfly stroke?", answer: "A stroke where both arms move forward simultaneously out of the water while the feet perform a dolphin kick" },
    { points: 800, question: "What is the Tour de France?", answer: "The most prestigious annual cycling race, spanning roughly 3,500 km across France" },
    { points: 800, question: "How many points is a 'Try' worth in rugby union?", answer: "5 points" },
    { points: 800, question: "What is the name of the ancient Greek running race that was the main event at the first Olympics?", answer: "The stadion race (a sprint roughly 192 metres)" },
    { points: 800, question: "In chess, which piece can only move diagonally?", answer: "The bishop" },
    { points: 800, question: "What does the term 'Grand Slam' mean in tennis?", answer: "Winning all four major tennis tournaments (Australian Open, French Open, Wimbledon, US Open) in one year" },
    // 1000 — Hard (8)
    { points: 1000, question: "What is Usain Bolt's 100m world record time set in 2009?", answer: "9.58 seconds" },
    { points: 1000, question: "What is the Fosbury Flop?", answer: "A high jump technique where the athlete goes over the bar headfirst and back-first, revolutionized by Dick Fosbury at the 1968 Olympics" },
    { points: 1000, question: "In cricket, what is the Duckworth-Lewis-Stern method used for?", answer: "Calculating revised target scores in rain-affected limited overs matches" },
    { points: 1000, question: "In which year did South Africa host and win the Rugby World Cup?", answer: "1995" },
    { points: 1000, question: "What is the minimum number of points needed to win a set in table tennis?", answer: "11 points (with a minimum 2-point lead)" },
    { points: 1000, question: "What chess term means placing a king so every move it makes puts it in check?", answer: "Stalemate (when the king has no legal moves but is not in check — results in a draw)" },
    { points: 1000, question: "What is the name of the penalty in football (soccer) for a goalkeeper picking up a deliberate back-pass from a teammate?", answer: "An indirect free kick is awarded to the opposing team" },
    { points: 1000, question: "What is the sequence of strokes in competitive swimming's individual medley?", answer: "Butterfly, Backstroke, Breaststroke, Freestyle" },
    // 1200 — Expert (8)
    { points: 1200, question: "What is the exact distance of a marathon in miles and yards?", answer: "26 miles 385 yards (approximately 26.22 miles)" },
    { points: 1200, question: "In fencing, what does the term 'touché' mean?", answer: "A hit scored on the opponent — an acknowledgment that a touch was made" },
    { points: 1200, question: "In Olympic archery, what is the shooting distance for the standard round?", answer: "70 metres" },
    { points: 1200, question: "What was the nationality of the first non-British driver to win the Formula 1 World Championship?", answer: "Argentine (Juan Manuel Fangio, 1951)" },
    { points: 1200, question: "What is the name of the official match ball used at the 2022 FIFA World Cup in Qatar?", answer: "Al Rihla (by Adidas)" },
    { points: 1200, question: "In rowing, what is the difference between 'sculling' and 'sweep rowing'?", answer: "In sculling, each rower uses two oars; in sweep rowing, each rower uses one oar" },
    { points: 1200, question: "What is the 'Flying Finn' nickname historically given to which legendary long-distance runner?", answer: "Paavo Nurmi (who won 9 Olympic gold medals in distance running in the 1920s)" },
    { points: 1200, question: "In curling, what is the term for the area at the end of the sheet where the stones must be delivered?", answer: "The house (the target circle at each end of the sheet)" },
  ],

  // ──────────────────────────────────────────────────────────── MOVIES & TV ─────
  "Movies & TV": [
    // 200 — Very Easy (9)
    { points: 200, question: "Which animated Disney film features a young lion named Simba?", answer: "The Lion King" },
    { points: 200, question: "Who played Iron Man in the Marvel Cinematic Universe?", answer: "Robert Downey Jr." },
    { points: 200, question: "What fictional school does Harry Potter attend?", answer: "Hogwarts School of Witchcraft and Wizardry" },
    { points: 200, question: "What TV show features a chemistry teacher who secretly becomes a drug kingpin?", answer: "Breaking Bad" },
    { points: 200, question: "What animated film features a clownfish searching for his son Nemo?", answer: "Finding Nemo" },
    { points: 200, question: "Who played Jack Dawson in the 1997 film Titanic?", answer: "Leonardo DiCaprio" },
    { points: 200, question: "What is the name of the cowboy toy in Toy Story?", answer: "Woody" },
    { points: 200, question: "What streaming platform produced the show Stranger Things?", answer: "Netflix" },
    { points: 200, question: "In what movie does a boy see dead people and the famous line 'I see dead people' appears?", answer: "The Sixth Sense" },
    // 400 — Easy (9)
    { points: 400, question: "Who directed The Dark Knight (2008) and Inception (2010)?", answer: "Christopher Nolan" },
    { points: 400, question: "In what year was the original Star Wars film (Episode IV: A New Hope) released?", answer: "1977" },
    { points: 400, question: "What is the name of the fictional African country in Black Panther?", answer: "Wakanda" },
    { points: 400, question: "Who played Jon Snow in Game of Thrones?", answer: "Kit Harington" },
    { points: 400, question: "Which actress played Katniss Everdeen in The Hunger Games films?", answer: "Jennifer Lawrence" },
    { points: 400, question: "Who directed the Lord of the Rings trilogy?", answer: "Peter Jackson" },
    { points: 400, question: "What 2019 Korean film won the Academy Award for Best Picture?", answer: "Parasite" },
    { points: 400, question: "What is the name of the TV sitcom set in a bar in Boston?", answer: "Cheers" },
    { points: 400, question: "Who composed the iconic music for the Star Wars series?", answer: "John Williams" },
    // 600 — Medium (8)
    { points: 600, question: "Who directed the 1968 science fiction epic 2001: A Space Odyssey?", answer: "Stanley Kubrick" },
    { points: 600, question: "What character does Marlon Brando play in The Godfather (1972)?", answer: "Vito Corleone" },
    { points: 600, question: "What film features the quote 'I'm going to make him an offer he can't refuse'?", answer: "The Godfather (1972)" },
    { points: 600, question: "In which city is the TV show Friends set?", answer: "New York City" },
    { points: 600, question: "What 1994 film stars Tom Hanks as a kind-hearted man sitting on a park bench?", answer: "Forrest Gump" },
    { points: 600, question: "What was the first feature-length animated film produced by Walt Disney?", answer: "Snow White and the Seven Dwarfs (1937)" },
    { points: 600, question: "Who plays Sherlock Holmes in the BBC television series Sherlock?", answer: "Benedict Cumberbatch" },
    { points: 600, question: "What Alfred Hitchcock film features a shocking murder in a shower scene at the Bates Motel?", answer: "Psycho (1960)" },
    // 800 — Medium-Hard (8)
    { points: 800, question: "In what year was the first Emmy Award ceremony held?", answer: "1949" },
    { points: 800, question: "Who played Hannibal Lecter in The Silence of the Lambs?", answer: "Anthony Hopkins" },
    { points: 800, question: "What is the name of the character played by Bryan Cranston in Breaking Bad?", answer: "Walter White" },
    { points: 800, question: "What film studio produced Shrek and Madagascar?", answer: "DreamWorks Animation" },
    { points: 800, question: "Who directed Schindler's List (1993)?", answer: "Steven Spielberg" },
    { points: 800, question: "In what year did The Sopranos premiere on HBO?", answer: "1999" },
    { points: 800, question: "What 2014 Alejandro González Iñárritu film won the Academy Award for Best Picture?", answer: "Birdman" },
    { points: 800, question: "In what film does Jack Nicholson deliver the line 'Here's Johnny!'?", answer: "The Shining (1980)" },
    // 1000 — Hard (8)
    { points: 1000, question: "Who plays the Joker in the 2019 standalone film Joker?", answer: "Joaquin Phoenix" },
    { points: 1000, question: "What French cinematic movement from the late 1950s–60s emphasised experimental techniques and was known as the 'New Wave'?", answer: "Nouvelle Vague" },
    { points: 1000, question: "What is the name of the fictional language spoken by the Na'vi in Avatar?", answer: "Na'vi" },
    { points: 1000, question: "Who directed Apocalypse Now (1979)?", answer: "Francis Ford Coppola" },
    { points: 1000, question: "What is the name of the camera technique where the camera zooms in while simultaneously moving backward, creating a disorienting effect?", answer: "Dolly zoom (also called the Hitchcock zoom or Vertigo effect)" },
    { points: 1000, question: "Who won the Academy Award for Best Actor for his role in Philadelphia (1993)?", answer: "Tom Hanks" },
    { points: 1000, question: "What 1985 Terry Gilliam film depicts a dystopian bureaucratic future?", answer: "Brazil" },
    { points: 1000, question: "What is the Bechdel test used to evaluate in films?", answer: "Whether a film has at least two named women who talk to each other about something other than a man" },
    // 1200 — Expert (8)
    { points: 1200, question: "What is the name of the Japanese animation studio behind Spirited Away and My Neighbor Totoro?", answer: "Studio Ghibli" },
    { points: 1200, question: "What 1922 silent horror film is an unauthorised adaptation of Bram Stoker's Dracula?", answer: "Nosferatu (Eine Symphonie des Grauens)" },
    { points: 1200, question: "What is the Kuleshov effect in filmmaking?", answer: "The psychological phenomenon where an audience derives meaning from a shot based on the shot that precedes it, not the shot itself" },
    { points: 1200, question: "Who directed the 1927 German Expressionist film Metropolis?", answer: "Fritz Lang" },
    { points: 1200, question: "Who composed the haunting theme music for the TV series Twin Peaks?", answer: "Angelo Badalamenti" },
    { points: 1200, question: "In which film does Orson Welles play the lead character Charles Foster Kane?", answer: "Citizen Kane (1941)" },
    { points: 1200, question: "What is the '180-degree rule' in filmmaking?", answer: "The rule that the camera should remain on one side of an imaginary line between characters to maintain consistent spatial orientation for the viewer" },
    { points: 1200, question: "What is 'mise-en-scène' in film theory?", answer: "The arrangement of all visual elements in a film frame — including sets, lighting, actors, and props — as an expressive tool" },
  ],

  // ─────────────────────────────────────────────────────────────────── MUSIC ────
  Music: [
    // 200 — Very Easy (9)
    { points: 200, question: "How many strings does a standard guitar have?", answer: "6 strings" },
    { points: 200, question: "Which band recorded 'Bohemian Rhapsody'?", answer: "Queen" },
    { points: 200, question: "How many notes are in a standard musical octave?", answer: "8 notes" },
    { points: 200, question: "What is the name of the band that Michael Jackson was part of before going solo?", answer: "The Jackson 5" },
    { points: 200, question: "Who is known as the 'Queen of Pop'?", answer: "Madonna" },
    { points: 200, question: "What does the Italian musical term 'piano' (as a dynamic marking) mean?", answer: "Soft / quiet" },
    { points: 200, question: "How many musicians are in a quartet?", answer: "4" },
    { points: 200, question: "What music streaming platform was founded in Sweden in 2006?", answer: "Spotify" },
    { points: 200, question: "What instrument does a DJ use to mix music?", answer: "Turntable (or DJ mixer / controller)" },
    // 400 — Easy (9)
    { points: 400, question: "In what year did Michael Jackson release the album 'Thriller'?", answer: "1982" },
    { points: 400, question: "Which British band sang 'Hey Jude' and 'Let It Be'?", answer: "The Beatles" },
    { points: 400, question: "What is the musical term for the speed at which a piece of music is played?", answer: "Tempo" },
    { points: 400, question: "Who is known as the 'King of Rock and Roll'?", answer: "Elvis Presley" },
    { points: 400, question: "What is the name of the highest-pitched voice in a choir?", answer: "Soprano" },
    { points: 400, question: "Who sang 'Rolling in the Deep' and 'Hello'?", answer: "Adele" },
    { points: 400, question: "What is the name of the band that featured Mick Jagger and Keith Richards?", answer: "The Rolling Stones" },
    { points: 400, question: "What genre of music originated in New Orleans combining blues, ragtime, and brass?", answer: "Jazz" },
    { points: 400, question: "What music award is considered the industry's equivalent of the Oscar?", answer: "The Grammy Award" },
    // 600 — Medium (8)
    { points: 600, question: "Who composed the opera 'The Magic Flute' (Die Zauberflöte)?", answer: "Wolfgang Amadeus Mozart" },
    { points: 600, question: "What is the musical term for the number of beats per measure indicated at the beginning of a piece?", answer: "Time signature" },
    { points: 600, question: "What is a musical composition written for a full orchestra called?", answer: "A symphony" },
    { points: 600, question: "What is 'a cappella' music?", answer: "Vocal music performed without any instrumental accompaniment" },
    { points: 600, question: "What is a musical arpeggio?", answer: "A chord where the notes are played in rapid succession rather than simultaneously" },
    { points: 600, question: "What type of instrument is a saxophone?", answer: "A woodwind instrument (with a single reed, played like a clarinet but made of brass)" },
    { points: 600, question: "What famous composer became progressively deaf yet continued to compose masterpieces?", answer: "Ludwig van Beethoven" },
    { points: 600, question: "What is the term for a melody sung simultaneously against another melody?", answer: "Counterpoint (countermelody)" },
    // 800 — Medium-Hard (8)
    { points: 800, question: "What is the name of the scale that includes all 12 half-steps within one octave?", answer: "The chromatic scale" },
    { points: 800, question: "What is a musical triplet?", answer: "A group of three notes played in the time normally occupied by two notes of the same value" },
    { points: 800, question: "What is the difference between major and minor keys in music?", answer: "Major keys generally sound brighter and happier; minor keys generally sound darker and sadder, due to different interval patterns" },
    { points: 800, question: "What is a musical 'fugue'?", answer: "A polyphonic composition in which a short melody (the subject) is introduced and then imitated successively at different pitches across multiple voices" },
    { points: 800, question: "Who composed 'The Four Seasons'?", answer: "Antonio Vivaldi" },
    { points: 800, question: "What is the name of the technique in string playing where the bow bounces lightly on the strings?", answer: "Spiccato" },
    { points: 800, question: "What is the blues scale?", answer: "A pentatonic minor scale with an added flattened fifth note (the 'blue note')" },
    { points: 800, question: "Who composed 'The Goldberg Variations'?", answer: "Johann Sebastian Bach" },
    // 1000 — Hard (8)
    { points: 1000, question: "What is the 12-tone composition technique developed by Arnold Schoenberg called?", answer: "Serialism (twelve-tone technique / dodecaphony)" },
    { points: 1000, question: "Who was the Russian composer of 'The Rite of Spring' (1913) whose premiere caused a near-riot?", answer: "Igor Stravinsky" },
    { points: 1000, question: "What is the musical term for a gradual decrease in tempo?", answer: "Rallentando (or ritardando)" },
    { points: 1000, question: "What is a 'cadenza' in a concerto?", answer: "A solo passage, often improvised, near the end of a movement in which the soloist displays their virtuosity" },
    { points: 1000, question: "What is 'sonata form' in classical music?", answer: "A musical structure with three sections: exposition (introduces themes), development (varies and develops themes), and recapitulation (restates themes)" },
    { points: 1000, question: "Who composed 'Don Giovanni'?", answer: "Wolfgang Amadeus Mozart" },
    { points: 1000, question: "What is the name of the technique where a singer uses a 'break' in their voice to move between registers?", answer: "Passaggio (the break between chest voice and head voice / falsetto)" },
    { points: 1000, question: "In what year did Beethoven complete his Ninth Symphony?", answer: "1824" },
    // 1200 — Expert (8)
    { points: 1200, question: "What is the difference between equal temperament and just intonation?", answer: "Equal temperament divides the octave into 12 mathematically equal half-steps; just intonation uses pure intervals based on small whole-number ratios, resulting in purer consonances but more complex key changes" },
    { points: 1200, question: "What is the term for the section of a symphony in sonata form that develops and transforms themes introduced in the exposition?", answer: "The development section" },
    { points: 1200, question: "What is the mathematical ratio of a perfect fifth in just intonation?", answer: "3:2" },
    { points: 1200, question: "What musical form involves two or more independent melodic lines played simultaneously?", answer: "Polyphony (counterpoint)" },
    { points: 1200, question: "What is the name of Dmitri Shostakovich's most famous symphony, often called the 'Leningrad Symphony'?", answer: "Symphony No. 7 in C major, Op. 60" },
    { points: 1200, question: "What is the 'Mannheim crescendo' in orchestral music?", answer: "A controlled, gradual crescendo technique developed by the Mannheim orchestra in the 18th century, rising from pianissimo to fortissimo" },
    { points: 1200, question: "What is serialism in music composition?", answer: "A compositional technique that uses an ordered series (of pitches, dynamics, rhythms, etc.) as the structural basis for a piece, ensuring no element is repeated before all others in the series appear" },
    { points: 1200, question: "What is the name of the interval between two notes where one is exactly double the frequency of the other?", answer: "An octave" },
  ],

  // ──────────────────────────────────────────────────────────── TECHNOLOGY ──────
  Technology: [
    // 200 — Very Easy (9)
    { points: 200, question: "What does 'CPU' stand for?", answer: "Central Processing Unit" },
    { points: 200, question: "What company makes the iPhone?", answer: "Apple" },
    { points: 200, question: "What does 'www' stand for in a web address?", answer: "World Wide Web" },
    { points: 200, question: "What keyboard shortcut is used to undo an action on most computers?", answer: "Ctrl+Z (or Cmd+Z on Mac)" },
    { points: 200, question: "What is the name of Google's mobile operating system?", answer: "Android" },
    { points: 200, question: "What does 'USB' stand for?", answer: "Universal Serial Bus" },
    { points: 200, question: "What is the world's most visited search engine?", answer: "Google" },
    { points: 200, question: "What social media platform is known for short videos?", answer: "TikTok" },
    { points: 200, question: "What does 'Wi-Fi' allow you to do?", answer: "Connect to the internet wirelessly" },
    // 400 — Easy (9)
    { points: 400, question: "Who co-founded Apple Inc. alongside Steve Jobs?", answer: "Steve Wozniak" },
    { points: 400, question: "In what year did Tim Berners-Lee propose the World Wide Web?", answer: "1989" },
    { points: 400, question: "What programming language was created by Guido van Rossum?", answer: "Python" },
    { points: 400, question: "What does 'RAM' stand for?", answer: "Random Access Memory" },
    { points: 400, question: "What does 'HTML' stand for?", answer: "Hypertext Markup Language" },
    { points: 400, question: "What company owns Instagram and WhatsApp?", answer: "Meta (formerly Facebook)" },
    { points: 400, question: "What is Apple's desktop operating system called?", answer: "macOS" },
    { points: 400, question: "What is a 'firewall' in computing?", answer: "A security system that monitors and controls incoming and outgoing network traffic based on security rules" },
    { points: 400, question: "What does 'PDF' stand for?", answer: "Portable Document Format" },
    // 600 — Medium (8)
    { points: 600, question: "What encryption standard replaced DES as the US federal standard in 2001?", answer: "AES (Advanced Encryption Standard)" },
    { points: 600, question: "What does 'HTTP' stand for?", answer: "Hypertext Transfer Protocol" },
    { points: 600, question: "What is Moore's Law?", answer: "The observation that the number of transistors on a microchip doubles approximately every two years, leading to exponential growth in computing power" },
    { points: 600, question: "What is the name of the protocol used to send email?", answer: "SMTP (Simple Mail Transfer Protocol)" },
    { points: 600, question: "What is the difference between RAM and ROM?", answer: "RAM (Random Access Memory) is volatile — it loses data when power is off; ROM (Read-Only Memory) is non-volatile — it retains data permanently" },
    { points: 600, question: "What programming paradigm uses 'objects' that contain both data and methods?", answer: "Object-Oriented Programming (OOP)" },
    { points: 600, question: "Who created the Linux kernel?", answer: "Linus Torvalds" },
    { points: 600, question: "What is the programming language primarily used for web page styling?", answer: "CSS (Cascading Style Sheets)" },
    // 800 — Medium-Hard (8)
    { points: 800, question: "What is the difference between IPv4 and IPv6?", answer: "IPv4 uses 32-bit addresses (~4.3 billion total); IPv6 uses 128-bit addresses (vastly larger address space to accommodate the growth of the internet)" },
    { points: 800, question: "What does a DNS server do?", answer: "Translates domain names (like google.com) into IP addresses that computers use to communicate" },
    { points: 800, question: "What is the CAP theorem in distributed systems?", answer: "A distributed system can only simultaneously guarantee two of three properties: Consistency, Availability, and Partition tolerance" },
    { points: 800, question: "What is the difference between a compiler and an interpreter?", answer: "A compiler translates source code into machine code all at once before execution; an interpreter executes source code line by line directly" },
    { points: 800, question: "In what year was the first iPhone released?", answer: "2007" },
    { points: 800, question: "What is the name of the Ethereum blockchain founder?", answer: "Vitalik Buterin" },
    { points: 800, question: "What is machine learning?", answer: "A branch of AI where systems learn patterns from data and improve their performance without being explicitly programmed for each task" },
    { points: 800, question: "What does 'API' stand for and what does it do?", answer: "Application Programming Interface — it defines rules for how software applications communicate and share data with each other" },
    // 1000 — Hard (8)
    { points: 1000, question: "What does 'HTTP' stand for?", answer: "Hypertext Transfer Protocol" },
    { points: 1000, question: "What is the Big O notation for binary search?", answer: "O(log n)" },
    { points: 1000, question: "What is the 'two's complement' representation used for in computing?", answer: "Representing both positive and negative integers in binary using a fixed number of bits" },
    { points: 1000, question: "What is the halting problem in computer science?", answer: "The problem of determining whether a given program will eventually halt or run forever — proven to be undecidable by Alan Turing" },
    { points: 1000, question: "What cryptographic protocol does HTTPS use to secure web communication?", answer: "TLS (Transport Layer Security), formerly known as SSL" },
    { points: 1000, question: "What is a 'race condition' in concurrent programming?", answer: "A bug where the outcome depends on the unpredictable order or timing of concurrent operations" },
    { points: 1000, question: "What is 'Docker' used for in software development?", answer: "Creating, deploying, and running applications in isolated containers, ensuring consistent behaviour across different environments" },
    { points: 1000, question: "What is SQL?", answer: "Structured Query Language — a domain-specific language used to manage and query relational databases" },
    // 1200 — Expert (8)
    { points: 1200, question: "What is the Church-Turing thesis?", answer: "The thesis that any effectively computable function can be computed by a Turing machine — defining the limits of what is computationally possible" },
    { points: 1200, question: "What is the Von Neumann architecture?", answer: "A computer design where the CPU, memory, and I/O are connected by a shared bus, with both program instructions and data stored in the same memory" },
    { points: 1200, question: "What is a man-in-the-middle (MITM) attack?", answer: "An attack where an adversary secretly intercepts and possibly alters communication between two parties who believe they are communicating directly" },
    { points: 1200, question: "What does the Nyquist-Shannon sampling theorem state?", answer: "A continuous signal can be perfectly reconstructed if it is sampled at a rate greater than twice its highest frequency" },
    { points: 1200, question: "What is 'Kubernetes'?", answer: "An open-source container orchestration system for automating deployment, scaling, and management of containerised applications" },
    { points: 1200, question: "What is the difference between deep learning and traditional machine learning?", answer: "Deep learning uses multi-layered neural networks to automatically learn features from raw data; traditional machine learning typically requires manual feature engineering" },
    { points: 1200, question: "What is the P vs NP problem?", answer: "The unresolved question of whether every problem whose solution can be quickly verified (NP) can also be quickly solved (P)" },
    { points: 1200, question: "What is a 'zero-day' vulnerability?", answer: "A software security flaw that is unknown to the software vendor and has no patch — it can be exploited immediately ('zero days' of warning)" },
  ],

  // ──────────────────────────────────────────────────────────── LITERATURE ──────
  Literature: [
    // 200 — Very Easy (9)
    { points: 200, question: "Who wrote 'Romeo and Juliet'?", answer: "William Shakespeare" },
    { points: 200, question: "What is the name of the boy who never grows up in J.M. Barrie's story?", answer: "Peter Pan" },
    { points: 200, question: "Who wrote 'Harry Potter and the Philosopher's Stone'?", answer: "J.K. Rowling" },
    { points: 200, question: "What is the name of the fictional detective who lives on Baker Street?", answer: "Sherlock Holmes" },
    { points: 200, question: "In Alice's Adventures in Wonderland, what does Alice follow down a rabbit hole?", answer: "A white rabbit" },
    { points: 200, question: "Who wrote the Diary of a Young Girl, a famous World War II memoir?", answer: "Anne Frank" },
    { points: 200, question: "What famous novel begins with 'It was the best of times, it was the worst of times'?", answer: "A Tale of Two Cities (by Charles Dickens)" },
    { points: 200, question: "Who is the name of the orphan boy in Charles Dickens' novel who asks for more food?", answer: "Oliver Twist" },
    { points: 200, question: "What is the name of the hobbit protagonist in 'The Hobbit'?", answer: "Bilbo Baggins" },
    // 400 — Easy (9)
    { points: 400, question: "In which novel does the wealthy and mysterious character Jay Gatsby appear?", answer: "The Great Gatsby (by F. Scott Fitzgerald)" },
    { points: 400, question: "Who wrote '1984' and 'Animal Farm'?", answer: "George Orwell" },
    { points: 400, question: "Who wrote 'Pride and Prejudice'?", answer: "Jane Austen" },
    { points: 400, question: "What is the famous opening line of Herman Melville's 'Moby-Dick'?", answer: "'Call me Ishmael.'" },
    { points: 400, question: "Who wrote 'Crime and Punishment'?", answer: "Fyodor Dostoevsky" },
    { points: 400, question: "What novel by Harper Lee addresses racial injustice in the American South?", answer: "To Kill a Mockingbird" },
    { points: 400, question: "Who is the author of 'The Alchemist' (O Alquimista)?", answer: "Paulo Coelho" },
    { points: 400, question: "Who wrote 'The Chronicles of Narnia'?", answer: "C.S. Lewis" },
    { points: 400, question: "Who wrote 'Don Quixote', considered the first modern European novel?", answer: "Miguel de Cervantes" },
    // 600 — Medium (8)
    { points: 600, question: "What is the subtitle of Mary Shelley's novel 'Frankenstein'?", answer: "The Modern Prometheus" },
    { points: 600, question: "Who wrote 'Paradise Lost'?", answer: "John Milton" },
    { points: 600, question: "In what language did Dante Alighieri originally write the 'Divine Comedy'?", answer: "Italian (Tuscan dialect)" },
    { points: 600, question: "What novel by James Joyce is considered one of the most complex works in the English language?", answer: "Ulysses" },
    { points: 600, question: "Who wrote 'The Metamorphosis' (Die Verwandlung)?", answer: "Franz Kafka" },
    { points: 600, question: "What is the name of the dystopian society in Margaret Atwood's 'The Handmaid's Tale'?", answer: "Gilead" },
    { points: 600, question: "What literary movement emphasised irrationality, dreams, and the unconscious mind?", answer: "Surrealism" },
    { points: 600, question: "Who wrote 'Middlemarch', often called the greatest novel in the English language?", answer: "George Eliot (pen name of Mary Ann Evans)" },
    // 800 — Medium-Hard (8)
    { points: 800, question: "What is the name of the narrator in Vladimir Nabokov's novel 'Lolita'?", answer: "Humbert Humbert" },
    { points: 800, question: "What is the stream of consciousness technique in literature?", answer: "A narrative mode that captures the continuous and often associative flow of a character's thoughts, feelings, and perceptions in real time" },
    { points: 800, question: "What is the name of the tragic hero in Shakespeare's play about a Danish prince who contemplates revenge?", answer: "Hamlet" },
    { points: 800, question: "What Nobel Prize-winning Colombian author wrote 'One Hundred Years of Solitude'?", answer: "Gabriel García Márquez" },
    { points: 800, question: "What is 'magical realism' as a literary genre?", answer: "A style where fantastical or magical elements appear naturally within otherwise realistic settings, treated as ordinary" },
    { points: 800, question: "Who wrote 'The Brothers Karamazov'?", answer: "Fyodor Dostoevsky" },
    { points: 800, question: "What is the 'unreliable narrator' technique in literature?", answer: "A narrative device where the storyteller's credibility is compromised, leaving the reader to question the accuracy of events described" },
    { points: 800, question: "What Russian author wrote both 'War and Peace' and 'Anna Karenina'?", answer: "Leo Tolstoy" },
    // 1000 — Hard (8)
    { points: 1000, question: "What is the name of the epic poem attributed to Homer that tells of Odysseus's journey home from Troy?", answer: "The Odyssey" },
    { points: 1000, question: "Who wrote 'Thus Spoke Zarathustra' (Also sprach Zarathustra)?", answer: "Friedrich Nietzsche" },
    { points: 1000, question: "Who wrote 'The Sound and the Fury'?", answer: "William Faulkner" },
    { points: 1000, question: "What is the term for a character who serves as a strong contrast to the main character, highlighting their traits?", answer: "A foil" },
    { points: 1000, question: "What is a literary 'flashback'?", answer: "A narrative device that interrupts the story to show events that happened earlier in time (also called analepsis)" },
    { points: 1000, question: "What is 'ekphrasis' in literature?", answer: "A vivid literary description of a work of visual art" },
    { points: 1000, question: "Who wrote 'The Canterbury Tales'?", answer: "Geoffrey Chaucer" },
    { points: 1000, question: "What is the term for the tragic flaw in a hero that leads to their downfall?", answer: "Hamartia" },
    // 1200 — Expert (8)
    { points: 1200, question: "What Japanese literary work from the Heian period (around 1000 AD) is considered one of the world's first novels?", answer: "The Tale of Genji (Genji Monogatari) by Murasaki Shikibu" },
    { points: 1200, question: "What is the difference between a simile and a metaphor?", answer: "A simile compares two things using 'like' or 'as'; a metaphor states one thing IS another, without the comparison words" },
    { points: 1200, question: "Who wrote 'The Waste Land' (1922), a landmark of modernist poetry?", answer: "T.S. Eliot" },
    { points: 1200, question: "What is 'Chekhov's Gun' as a literary principle?", answer: "The dramatic principle that every element introduced in a story must serve a purpose — if a gun is shown in Act 1, it must be fired by Act 3" },
    { points: 1200, question: "What Latin American literary movement in the 1960s–70s produced 'One Hundred Years of Solitude'?", answer: "El Boom (the Latin American literary boom)" },
    { points: 1200, question: "What is 'in medias res' as a narrative technique?", answer: "Beginning a story in the middle of the action rather than at the chronological beginning" },
    { points: 1200, question: "What is the name of the ancient Sanskrit epic attributed to the sage Valmiki?", answer: "The Ramayana" },
    { points: 1200, question: "Who wrote 'Absalom, Absalom!' (1936), a novel about the decline of a Southern dynasty?", answer: "William Faulkner" },
  ],

  // ──────────────────────────────────────────────────────────────────── ART ─────
  Art: [
    // 200 — Very Easy (9)
    { points: 200, question: "Who painted the Mona Lisa?", answer: "Leonardo da Vinci" },
    { points: 200, question: "What are the three primary colours (in traditional painting)?", answer: "Red, blue, and yellow" },
    { points: 200, question: "What museum in Paris houses the Mona Lisa?", answer: "The Louvre" },
    { points: 200, question: "Who painted the Sistine Chapel ceiling?", answer: "Michelangelo" },
    { points: 200, question: "What colour do you get by mixing red and blue?", answer: "Purple" },
    { points: 200, question: "What is the name of the art form that involves folding paper into shapes?", answer: "Origami" },
    { points: 200, question: "What tool does a painter use to apply paint to a canvas?", answer: "A paintbrush" },
    { points: 200, question: "What is a self-portrait?", answer: "A portrait of an artist made by the artist themselves" },
    { points: 200, question: "What colour do you get by mixing red and white?", answer: "Pink" },
    // 400 — Easy (9)
    { points: 400, question: "Which Spanish artist co-founded the Cubist movement?", answer: "Pablo Picasso" },
    { points: 400, question: "In which century did the Italian Renaissance begin?", answer: "The 14th century (1300s)" },
    { points: 400, question: "Which Dutch Golden Age painter created 'Girl with a Pearl Earring'?", answer: "Johannes Vermeer" },
    { points: 400, question: "Who painted 'The Starry Night'?", answer: "Vincent van Gogh" },
    { points: 400, question: "Who sculpted the famous statue 'David'?", answer: "Michelangelo" },
    { points: 400, question: "What is the technique of painting on wet plaster called?", answer: "Fresco" },
    { points: 400, question: "What is the name of the art movement that used bright, non-naturalistic colours?", answer: "Fauvism" },
    { points: 400, question: "What technique involves creating art by pasting various materials (photos, paper, fabric) onto a surface?", answer: "Collage" },
    { points: 400, question: "What is the arrangement of visual elements within a work of art called?", answer: "Composition" },
    // 600 — Medium (8)
    { points: 600, question: "What is the term for applying paint so thickly it creates a textured, three-dimensional surface?", answer: "Impasto" },
    { points: 600, question: "Who sculpted 'The Thinker'?", answer: "Auguste Rodin" },
    { points: 600, question: "Who painted 'The Persistence of Memory' — the famous painting with melting clocks?", answer: "Salvador Dalí" },
    { points: 600, question: "What is the Japanese art of ink wash painting called?", answer: "Sumi-e" },
    { points: 600, question: "What is pointillism?", answer: "A painting technique using tiny dots of pure colour placed side by side to form an image (pioneered by Georges Seurat)" },
    { points: 600, question: "What art movement used imagery from mass media and advertising, associated with Andy Warhol?", answer: "Pop Art" },
    { points: 600, question: "Who is known for painting large colourful flower paintings and the New Mexico landscape?", answer: "Georgia O'Keeffe" },
    { points: 600, question: "What is chiaroscuro in painting?", answer: "The dramatic use of strong contrast between light and dark to create a sense of depth and three-dimensionality" },
    // 800 — Medium-Hard (8)
    { points: 800, question: "What is 'trompe-l'œil' in art?", answer: "A painting technique that creates a realistic optical illusion of three-dimensional objects on a flat surface (French for 'deceives the eye')" },
    { points: 800, question: "Who founded the Bauhaus school of art and design in Germany in 1919?", answer: "Walter Gropius" },
    { points: 800, question: "What is the Golden Ratio and how is it used in art?", answer: "A mathematical ratio of approximately 1.618:1 found in nature and used in art and architecture to create visually harmonious proportions" },
    { points: 800, question: "What is lithography in printmaking?", answer: "A printing technique using a flat stone or metal plate treated with a greasy substance to hold ink, based on the repulsion of oil and water" },
    { points: 800, question: "Who painted 'American Gothic' (1930)?", answer: "Grant Wood" },
    { points: 800, question: "Who created the 'readymades' concept — using everyday objects as fine art?", answer: "Marcel Duchamp (e.g., his famous urinal sculpture 'Fountain', 1917)" },
    { points: 800, question: "What is the name of the French Impressionist most famous for painting ballerina scenes?", answer: "Edgar Degas" },
    { points: 800, question: "What painting technique uses egg yolk as the binding medium?", answer: "Egg tempera" },
    // 1000 — Hard (8)
    { points: 1000, question: "What is 'sfumato' in Renaissance painting?", answer: "Leonardo da Vinci's technique of blending colours and tones so smoothly there are no sharp outlines — literally 'vanished like smoke' in Italian" },
    { points: 1000, question: "Who were the three great masters of the High Italian Renaissance?", answer: "Leonardo da Vinci, Michelangelo, and Raphael" },
    { points: 1000, question: "What is the name of the Japanese woodblock print art tradition?", answer: "Ukiyo-e (literally 'pictures of the floating world')" },
    { points: 1000, question: "What did the Dadaist art movement believe?", answer: "That traditional art was meaningless after the horrors of World War I; they embraced irrationality, absurdity, and rejected conventional aesthetics" },
    { points: 1000, question: "What is the difference between abstract and non-objective art?", answer: "Abstract art is distorted or simplified from reality; non-objective art has no reference to the real world at all" },
    { points: 1000, question: "What is the branch of philosophy concerned with the nature and appreciation of art and beauty?", answer: "Aesthetics" },
    { points: 1000, question: "What is encaustic painting?", answer: "An ancient painting technique that uses pigments mixed with hot wax as the binding medium" },
    { points: 1000, question: "What is the name of the Flemish master famous for large allegorical paintings such as 'The Garden of Earthly Delights'?", answer: "Hieronymus Bosch" },
    // 1200 — Expert (8)
    { points: 1200, question: "What is the term for the branch of philosophy concerned with beauty, art, and taste?", answer: "Aesthetics" },
    { points: 1200, question: "What was the name of the avant-garde movement co-founded by Wassily Kandinsky that emphasised spiritual values in abstract form?", answer: "Der Blaue Reiter (The Blue Rider)" },
    { points: 1200, question: "What is 'grisaille' in painting?", answer: "A monochromatic painting technique executed entirely in shades of grey, sometimes used as an underpainting or to simulate stone sculpture" },
    { points: 1200, question: "What is 'pentimento' in art?", answer: "Evidence of an earlier painting or drawing that becomes visible through the outer layers of paint as it ages and becomes transparent" },
    { points: 1200, question: "What is the art criticism theory developed by Clement Greenberg that championed abstraction and 'pure' art forms?", answer: "Formalism (Greenbergian formalism)" },
    { points: 1200, question: "Who created the concept of 'action painting' associated with Abstract Expressionism?", answer: "Jackson Pollock (known for his drip painting technique)" },
    { points: 1200, question: "What painting medium uses a polymer emulsion as the binder, allowing fast drying and water cleanup?", answer: "Acrylic paint" },
    { points: 1200, question: "What is the name of the ancient Roman painting technique preserved in Pompeii where pigments were mixed into wet lime plaster?", answer: "Fresco (buon fresco)" },
  ],

  // ──────────────────────────────────────────────────────────── FOOD & DRINK ────
  "Food & Drink": [
    // 200 — Very Easy (9)
    { points: 200, question: "What fruit is the main ingredient in guacamole?", answer: "Avocado" },
    { points: 200, question: "From which country does pizza originally come?", answer: "Italy" },
    { points: 200, question: "What is the main ingredient in bread?", answer: "Flour (wheat)" },
    { points: 200, question: "What drink is made from fermented grapes?", answer: "Wine" },
    { points: 200, question: "What is the name of the Japanese dish of vinegared rice combined with seafood or vegetables?", answer: "Sushi" },
    { points: 200, question: "What is the most commonly drunk beverage in the world after water?", answer: "Tea" },
    { points: 200, question: "What sweet condiment is made by bees?", answer: "Honey" },
    { points: 200, question: "What is the name of the drink made by brewing roasted ground coffee beans?", answer: "Coffee" },
    { points: 200, question: "What is the main flavour ingredient that gives curry its yellow colour?", answer: "Turmeric" },
    // 400 — Easy (9)
    { points: 400, question: "What is the Japanese alcoholic drink made from fermented rice?", answer: "Sake" },
    { points: 400, question: "What country is famous for its Gouda and Edam cheeses?", answer: "The Netherlands" },
    { points: 400, question: "What is the main ingredient in hummus?", answer: "Chickpeas (garbanzo beans)" },
    { points: 400, question: "What country is widely credited as the birthplace of croissants?", answer: "France (though inspired by the Austrian kipferl)" },
    { points: 400, question: "What is the name of the Indian clay oven used for cooking flatbreads and meats?", answer: "Tandoor (the cooking technique is called tandoori)" },
    { points: 400, question: "What is the difference between espresso and regular brewed coffee?", answer: "Espresso forces hot water under high pressure through finely-ground coffee, producing a concentrated shot; regular coffee uses slower brewing methods" },
    { points: 400, question: "What is sashimi?", answer: "A Japanese dish of fresh raw fish (or seafood) sliced thinly and served without rice" },
    { points: 400, question: "What vegetable is primarily used to make traditional kimchi?", answer: "Napa cabbage (baechu)" },
    { points: 400, question: "What type of pasta is shaped like long hollow tubes?", answer: "Penne (or rigatoni, ziti — any tubular pasta)" },
    // 600 — Medium (8)
    { points: 600, question: "What expensive spice comes from the dried stigmas of Crocus sativus flowers?", answer: "Saffron" },
    { points: 600, question: "What French cooking technique involves cooking vacuum-sealed food in a temperature-controlled water bath?", answer: "Sous vide" },
    { points: 600, question: "What is 'umami' as a taste?", answer: "The fifth basic taste (alongside sweet, sour, salty, and bitter) — often described as savoury or meaty" },
    { points: 600, question: "What is the origin country of kimchi?", answer: "South Korea" },
    { points: 600, question: "What is the name of the Moroccan slow-cooked stew prepared in a conical clay pot of the same name?", answer: "Tagine" },
    { points: 600, question: "What is 'prosciutto'?", answer: "An Italian dry-cured ham that is thinly sliced and typically served uncooked" },
    { points: 600, question: "What makes sourdough bread different from regular bread?", answer: "Sourdough is leavened by wild yeast and bacteria (a sourdough starter) rather than commercial yeast, giving it a distinctive tangy flavour" },
    { points: 600, question: "What is 'blanching' in cooking?", answer: "Briefly cooking food in boiling water then immediately plunging it into ice water to stop cooking and preserve colour" },
    // 800 — Medium-Hard (8)
    { points: 800, question: "What chemical reaction between amino acids and sugars causes food to brown when cooked at high heat?", answer: "The Maillard reaction" },
    { points: 800, question: "What is the name of the ancient Roman fish sauce used as a condiment?", answer: "Garum" },
    { points: 800, question: "What is the culinary technique of 'confit'?", answer: "Slow-cooking food submerged in its own fat at a low temperature for a long time (e.g., duck confit)" },
    { points: 800, question: "What is the difference between a 'stock' and a 'broth' in cooking?", answer: "Stock is made primarily from bones (rich in gelatin); broth is made primarily from meat. Both use aromatics." },
    { points: 800, question: "In which region of Spain does paella originate?", answer: "Valencia" },
    { points: 800, question: "What is 'molecular gastronomy'?", answer: "A scientific approach to cooking that applies chemistry and physics techniques to create novel textures, flavours, and presentations" },
    { points: 800, question: "What is 'umeboshi'?", answer: "Japanese pickled plums (actually a variety of apricot) preserved in salt — intensely sour and salty, used in Japanese cuisine" },
    { points: 800, question: "What is the Korean fermented chilli paste used widely in Korean cooking?", answer: "Gochujang" },
    // 1000 — Hard (8)
    { points: 1000, question: "What chemical compound is responsible for the spicy heat in chilli peppers?", answer: "Capsaicin" },
    { points: 1000, question: "What is the name of the yeast strain used in most wine and beer fermentation?", answer: "Saccharomyces cerevisiae" },
    { points: 1000, question: "What is 'terroir' in the context of wine?", answer: "The complete natural environment — soil, climate, topography, and local microbes — that shapes a wine's unique character and flavour" },
    { points: 1000, question: "What is 'rendering' in cooking?", answer: "Slowly melting and extracting fat from meat or fat tissue over low heat" },
    { points: 1000, question: "What is the Scoville scale used for?", answer: "Measuring the heat (pungency) of chilli peppers and spicy foods by quantifying their capsaicin concentration" },
    { points: 1000, question: "What is 'koji' in Japanese food fermentation?", answer: "The mould Aspergillus oryzae, used to ferment staples like miso, sake, soy sauce, and mirin" },
    { points: 1000, question: "What is Parmigiano-Reggiano and where must it be produced to carry that name?", answer: "An Italian hard cheese made from raw cow's milk and aged at least 12 months, legally protected and only produced in the Parma, Reggio Emilia, and adjacent areas of Italy" },
    { points: 1000, question: "What is the French culinary concept 'mise en place'?", answer: "A French phrase meaning 'everything in its place' — the practice of preparing and organising all ingredients before cooking begins" },
    // 1200 — Expert (8)
    { points: 1200, question: "What enzymatic reaction causes a cut apple to turn brown when exposed to air?", answer: "Oxidation (enzymatic browning) catalysed by the enzyme polyphenol oxidase, which reacts with oxygen to oxidise phenolic compounds" },
    { points: 1200, question: "What is 'transglutaminase' and how is it used in cooking?", answer: "An enzyme nicknamed 'meat glue' that bonds proteins together — used in modernist cuisine to combine different proteins into a single piece" },
    { points: 1200, question: "At approximately what temperature (in Celsius) does the Maillard reaction occur?", answer: "Approximately 140–165°C (284–329°F)" },
    { points: 1200, question: "What is the difference between kefir and yogurt?", answer: "Kefir is fermented with a symbiotic culture of bacteria and yeast (kefir grains), resulting in a thinner, mildly effervescent drink; yogurt uses only bacteria and is thicker" },
    { points: 1200, question: "What is 'escabeche'?", answer: "A Mediterranean/Latin American technique of marinating and preserving cooked fish or meat in a vinegar and spice sauce" },
    { points: 1200, question: "What chemical process makes meat more tender when marinated in acidic ingredients like citrus juice or vinegar?", answer: "Acid denaturation — the acid disrupts protein structures (collagen and muscle fibres), softening the texture" },
    { points: 1200, question: "What is the French cooking term for gently sweating aromatic vegetables in butter over low heat until soft but not coloured?", answer: "Suer (sweating) — cooking without browning to release flavour gently" },
    { points: 1200, question: "What is the name of the Japanese technique of cooking fish by briefly searing it and then plunging it in ice water to create a contrasting texture?", answer: "Tataki — lightly seared on the outside, raw inside, then sliced thinly" },
  ],

  // ──────────────────────────────────────────────────────────────── NATURE ──────
  Nature: [
    // 200 — Very Easy (9)
    { points: 200, question: "What is the largest animal on Earth?", answer: "The blue whale" },
    { points: 200, question: "What do caterpillars transform into?", answer: "Butterflies (or moths)" },
    { points: 200, question: "How many legs does a spider have?", answer: "8 legs" },
    { points: 200, question: "What is the name of the process by which water evaporates, forms clouds, and falls as rain?", answer: "The water cycle (hydrological cycle)" },
    { points: 200, question: "What is the most abundant gas in Earth's atmosphere?", answer: "Nitrogen (~78%)" },
    { points: 200, question: "What do we call an animal that eats only plants?", answer: "A herbivore" },
    { points: 200, question: "What is Earth's natural satellite called?", answer: "The Moon" },
    { points: 200, question: "What is the largest land animal?", answer: "The African elephant" },
    { points: 200, question: "What do we call animals that are active at night?", answer: "Nocturnal animals" },
    // 400 — Easy (9)
    { points: 400, question: "How many bones does an adult human body have?", answer: "206 bones" },
    { points: 400, question: "What is the name of the largest species of shark?", answer: "The whale shark" },
    { points: 400, question: "How long does it take for Earth to orbit the Sun?", answer: "Approximately 365.25 days (1 year)" },
    { points: 400, question: "What colour is chlorophyll — the pigment that makes plants green?", answer: "Green" },
    { points: 400, question: "What is the name of the process by which a tadpole becomes a frog?", answer: "Metamorphosis" },
    { points: 400, question: "What type of animal is a dolphin?", answer: "A mammal" },
    { points: 400, question: "What percentage of Earth's surface is covered by water?", answer: "Approximately 71%" },
    { points: 400, question: "What is the study of living organisms called?", answer: "Biology" },
    { points: 400, question: "What is the name of the layer of Earth between the crust and the core?", answer: "The mantle" },
    // 600 — Medium (8)
    { points: 600, question: "What is the name of the deepest known point in the ocean?", answer: "Challenger Deep (in the Mariana Trench)" },
    { points: 600, question: "What is the term for an animal that is active during twilight hours — dawn and dusk?", answer: "Crepuscular" },
    { points: 600, question: "What is the name of the warm ocean current that keeps Western Europe milder than other regions at the same latitude?", answer: "The Gulf Stream (North Atlantic Current)" },
    { points: 600, question: "What is the difference between a stalactite and a stalagmite in caves?", answer: "Stalactites hang down from the ceiling; stalagmites grow up from the floor" },
    { points: 600, question: "What is a 'constellation'?", answer: "A group of stars forming a recognisable pattern or shape, traditionally named after mythological figures, animals, or objects" },
    { points: 600, question: "What is the name for the layer of Earth where we find most earthquakes and volcanoes?", answer: "The lithosphere (the outermost solid layer, including the crust and upper mantle)" },
    { points: 600, question: "What is the term for an organism that obtains energy by breaking down dead organic matter?", answer: "A decomposer (or detritivore)" },
    { points: 600, question: "What is the name of the process by which water moves from the roots to the leaves of a plant?", answer: "Transpiration (as part of the larger process of osmosis and capillary action)" },
    // 800 — Medium-Hard (8)
    { points: 800, question: "What is the scientific term for the process by which trees shed their leaves in autumn?", answer: "Abscission" },
    { points: 800, question: "What is the term for the geographic area that an animal defends against others of the same species?", answer: "A territory" },
    { points: 800, question: "What is the name of the weather phenomenon where the central and eastern Pacific Ocean becomes unusually warm?", answer: "El Niño" },
    { points: 800, question: "What type of rock is formed from compressed layers of sediment over long periods?", answer: "Sedimentary rock" },
    { points: 800, question: "What is the name for the large-scale ocean circulation driven by temperature and salinity differences?", answer: "Thermohaline circulation (also called the ocean conveyor belt)" },
    { points: 800, question: "What is the symbiotic relationship between the clownfish and the sea anemone classified as?", answer: "Mutualism — both species benefit (the clownfish gains protection; the anemone is kept clean)" },
    { points: 800, question: "What is a 'keystone species'?", answer: "A species that has a disproportionately large effect on its ecosystem relative to its abundance — its removal would significantly alter the ecosystem" },
    { points: 800, question: "What is the approximate number of neurons in the human brain?", answer: "About 86 billion neurons" },
    // 1000 — Hard (8)
    { points: 1000, question: "What is the Coriolis effect in weather systems?", answer: "The deflection of winds and ocean currents caused by Earth's rotation — to the right in the Northern Hemisphere, to the left in the Southern Hemisphere" },
    { points: 1000, question: "What is the name of the phenomenon where cold, nutrient-rich water rises to the ocean surface?", answer: "Upwelling" },
    { points: 1000, question: "What is the term for the zone of the ocean where sunlight does not penetrate?", answer: "The aphotic zone (also called the midnight zone or bathypelagic zone)" },
    { points: 1000, question: "What is nitrogen fixation?", answer: "The biological process by which certain bacteria convert atmospheric nitrogen gas (N₂) into ammonia (NH₃), which plants can use" },
    { points: 1000, question: "What is the scientific term for the process that maintains constant internal conditions in a living organism?", answer: "Homeostasis" },
    { points: 1000, question: "What is the name of the biological process by which animals return to their exact birthplace to reproduce?", answer: "Natal philopatry (or natal homing)" },
    { points: 1000, question: "What is the Geological time period known as the Mesozoic Era divided into?", answer: "Three periods: Triassic, Jurassic, and Cretaceous" },
    { points: 1000, question: "What is the name of the geologic time scale epoch we currently live in?", answer: "The Holocene epoch (some scientists argue we have entered the Anthropocene)" },
    // 1200 — Expert (8)
    { points: 1200, question: "What is the difference between mitosis and meiosis?", answer: "Mitosis produces two genetically identical diploid cells (for growth and repair); meiosis produces four genetically diverse haploid cells (for sexual reproduction)" },
    { points: 1200, question: "What enzyme in cells breaks down hydrogen peroxide to protect them from oxidative damage?", answer: "Catalase" },
    { points: 1200, question: "What is the name of the imaginary line dividing the Earth into Eastern and Western hemispheres?", answer: "The Prime Meridian (0° longitude)" },
    { points: 1200, question: "What is 'species richness' in ecology?", answer: "The number of different species present in a particular area — a key measure of biodiversity" },
    { points: 1200, question: "What is an 'extremophile'?", answer: "An organism that thrives in extreme environmental conditions such as very high/low temperatures, high salinity, or extreme acidity or alkalinity" },
    { points: 1200, question: "What is the approximate depth of the ocean's abyssal zone in kilometres?", answer: "Approximately 3–6 km (3,000–6,000 metres)" },
    { points: 1200, question: "What is the name of the process by which land-living organisms evolved from aquatic ancestors?", answer: "Terrestrialisation (the colonisation of land by aquatic organisms, beginning around 375 million years ago)" },
    { points: 1200, question: "What is the 'biomagnification' concept in ecology?", answer: "The increasing concentration of a toxic substance (like mercury or DDT) in the tissues of organisms at each successively higher level of the food chain" },
  ],

  // ──────────────────────────────────────────────────────────────── POLITICS ────
  Politics: [
    // 200 — Very Easy (9)
    { points: 200, question: "How many permanent members does the UN Security Council have?", answer: "5 permanent members" },
    { points: 200, question: "What does 'NATO' stand for?", answer: "North Atlantic Treaty Organization" },
    { points: 200, question: "What is a democracy?", answer: "A system of government where power belongs to the people, typically exercised through elected representatives" },
    { points: 200, question: "What does 'OPEC' stand for?", answer: "Organization of the Petroleum Exporting Countries" },
    { points: 200, question: "What is the capital city of the United States?", answer: "Washington, D.C." },
    { points: 200, question: "What is the name of the governing document of the United States?", answer: "The Constitution" },
    { points: 200, question: "How many countries are members of the United Nations (approximately)?", answer: "193 member states" },
    { points: 200, question: "What is the legislative body that makes laws in the United States called?", answer: "Congress (divided into the Senate and the House of Representatives)" },
    { points: 200, question: "What is the term for a system run by one person with absolute power?", answer: "Dictatorship (autocracy)" },
    // 400 — Easy (9)
    { points: 400, question: "What political system divides power between a central government and regional governments?", answer: "Federalism" },
    { points: 400, question: "In what year was the Universal Declaration of Human Rights adopted by the United Nations?", answer: "1948" },
    { points: 400, question: "What is the name of the building where the United States Congress meets?", answer: "The United States Capitol Building" },
    { points: 400, question: "What is the difference between a republic and a direct democracy?", answer: "A republic uses elected representatives to make decisions; a direct democracy allows citizens to vote directly on all laws" },
    { points: 400, question: "What is the legislative body of the United Kingdom called?", answer: "Parliament (comprising the House of Commons and the House of Lords)" },
    { points: 400, question: "What is a formal agreement between two or more countries called?", answer: "A treaty" },
    { points: 400, question: "Who was the first leader of the Soviet Union?", answer: "Vladimir Lenin" },
    { points: 400, question: "What is the term for the branch of government that interprets laws?", answer: "The judiciary (or judicial branch)" },
    { points: 400, question: "What country is the home of the world's oldest Parliament (the Althing)?", answer: "Iceland (founded in 930 AD)" },
    // 600 — Medium (8)
    { points: 600, question: "Who was the first Secretary-General of the United Nations?", answer: "Trygve Lie (of Norway)" },
    { points: 600, question: "What Latin term describes the legal principle that past court decisions must be followed in similar future cases?", answer: "Stare decisis" },
    { points: 600, question: "What is 'proportional representation' in electoral systems?", answer: "A voting system where the percentage of seats a party receives in the legislature corresponds to the percentage of votes it won" },
    { points: 600, question: "What is the difference between a parliamentary and a presidential system of government?", answer: "In a parliamentary system, the head of government (Prime Minister) comes from and is accountable to the legislature; in a presidential system, the executive is separately elected and independent" },
    { points: 600, question: "What is 'veto power' in the UN Security Council?", answer: "The ability of any of the 5 permanent members (US, UK, France, Russia, China) to block any resolution by voting against it" },
    { points: 600, question: "What is the name of the founding treaty of the European Union?", answer: "The Treaty of Maastricht (signed in 1992)" },
    { points: 600, question: "What is 'gerrymandering'?", answer: "Manipulating the boundaries of electoral districts to give one political party an unfair advantage" },
    { points: 600, question: "What is the political theory developed by Karl Marx called?", answer: "Marxism (or scientific socialism / historical materialism)" },
    // 800 — Medium-Hard (8)
    { points: 800, question: "What is the 'social contract' theory in political philosophy?", answer: "The idea that individuals give up certain freedoms to a governing authority in exchange for protection of their remaining rights — associated with Locke, Rousseau, and Hobbes" },
    { points: 800, question: "What is the 'Westphalian system' in international relations?", answer: "The international system of sovereign nation-states that recognise each other's right to rule within their own borders without external interference, originating from the 1648 Peace of Westphalia" },
    { points: 800, question: "What is the 'democratic peace theory'?", answer: "The observation that democratic countries rarely go to war with each other — one of the most robust empirical findings in political science" },
    { points: 800, question: "What is 'soft power' in international relations?", answer: "A country's ability to influence others through attraction, culture, values, and policies rather than through military or economic coercion" },
    { points: 800, question: "What is 'habeas corpus'?", answer: "The legal right requiring that a person who has been arrested must be brought before a judge — a fundamental protection against unlawful detention" },
    { points: 800, question: "What is the doctrine of 'judicial review' in the United States?", answer: "The power of the Supreme Court to declare laws unconstitutional — established by the landmark case Marbury v. Madison (1803)" },
    { points: 800, question: "What is the UN's 'Responsibility to Protect' (R2P) doctrine?", answer: "The international principle that sovereign states have a duty to protect their populations from mass atrocities, and the international community may intervene if a state fails to do so" },
    { points: 800, question: "What is 'nationalism' as a political doctrine?", answer: "The belief that people who share a national identity should govern themselves in their own independent state" },
    // 1000 — Hard (8)
    { points: 1000, question: "What is the 'Overton Window' in political science?", answer: "The range of policies and ideas that the general public will currently accept as reasonable — ideas outside this window are seen as radical or unthinkable" },
    { points: 1000, question: "What is the 'prisoners' dilemma' in game theory and its relevance to politics?", answer: "A scenario where two rational actors both choose self-interest and end up worse off than if they had cooperated — illustrates why international cooperation is difficult" },
    { points: 1000, question: "What is the difference between 'de jure' and 'de facto' sovereignty?", answer: "De jure sovereignty is recognised in law and by other states; de facto sovereignty is actual control over a territory regardless of legal recognition" },
    { points: 1000, question: "What is the 'realist' school of thought in international relations?", answer: "The theory that states are self-interested actors in an anarchic international system, and that power and security are the primary drivers of their behaviour" },
    { points: 1000, question: "What is the Treaty on the Non-Proliferation of Nuclear Weapons (NPT)?", answer: "An international treaty that aims to prevent the spread of nuclear weapons, promote disarmament, and ensure peaceful use of nuclear technology" },
    { points: 1000, question: "What is 'multilateralism' in international relations?", answer: "The coordination of foreign policy among multiple countries — often through international institutions, agreements, or coordinated diplomatic efforts" },
    { points: 1000, question: "What is 'lobbying' and why is it controversial?", answer: "The organised effort to influence government decisions on behalf of a group; controversial because it may give disproportionate political power to wealthy or well-organised interest groups" },
    { points: 1000, question: "What is the 'liberal institutionalist' school of international relations?", answer: "The theory that international institutions, laws, and cooperation can overcome anarchy and promote peace — in contrast to realism" },
    // 1200 — Expert (8)
    { points: 1200, question: "What is 'Arrow's Impossibility Theorem' in political science?", answer: "The mathematical proof by Kenneth Arrow that no ranked voting system can simultaneously satisfy all of a set of 'fair' criteria when there are three or more candidates" },
    { points: 1200, question: "What is the difference between 'deontological' and 'consequentialist' ethics in political philosophy?", answer: "Deontological ethics judges actions by adherence to rules and duties regardless of outcomes; consequentialist ethics judges actions solely by their results" },
    { points: 1200, question: "What is the Gini coefficient used to measure?", answer: "Income or wealth inequality within a population — 0 represents perfect equality, 1 (or 100%) represents maximum inequality" },
    { points: 1200, question: "What is 'subsidiarity' as a principle in European Union law?", answer: "The principle that decisions should be made at the most local level of government possible, with higher levels only acting when local levels cannot effectively address the issue" },
    { points: 1200, question: "What are Max Weber's three types of political authority (legitimacy)?", answer: "Traditional authority (custom and tradition), charismatic authority (personal qualities of a leader), and rational-legal authority (rules and laws)" },
    { points: 1200, question: "What is 'popular sovereignty'?", answer: "The principle that the authority of a government is derived from and legitimised by the consent of the people it governs" },
    { points: 1200, question: "What is the 'Responsibility to Protect' doctrine's three pillars?", answer: "1) State responsibility to protect its citizens; 2) International assistance to help states fulfil this duty; 3) International intervention when states manifestly fail to protect" },
    { points: 1200, question: "What political philosopher wrote 'A Theory of Justice' (1971), reviving liberal political philosophy?", answer: "John Rawls" },
  ],

};
