-- ============================================================
-- Omni-Verse — Question Seed File (50 questions per category)
-- Run this in the Supabase SQL Editor to populate the database.
-- WARNING: This deletes ALL existing questions first.
-- ============================================================

-- 1. Clear existing questions
DELETE FROM questions;

-- 2. SCIENCE (50 questions)
INSERT INTO questions (category_id, points, question_en, answer_en, question_ar, answer_ar)
SELECT c.id, q.pts, q.q_en, q.a_en, '', ''
FROM categories c
CROSS JOIN (VALUES
  (200,  'How many planets are in our solar system?',                                                'Eight'),
  (200,  'What is the boiling point of water in Celsius?',                                          '100°C'),
  (200,  'What is the chemical formula for water?',                                                 'H₂O'),
  (200,  'What organ pumps blood through the human body?',                                          'The heart'),
  (200,  'What force keeps us on the ground?',                                                      'Gravity'),
  (200,  'What is the closest star to Earth?',                                                      'The Sun'),
  (200,  'What gas do plants absorb to make their food?',                                           'Carbon dioxide (CO₂)'),
  (200,  'What type of animal is a whale?',                                                         'A mammal'),
  (200,  'What do we call the center of an atom?',                                                  'The nucleus'),
  (400,  'What is the chemical symbol for gold?',                                                   'Au'),
  (400,  'What planet is known as the Red Planet?',                                                 'Mars'),
  (400,  'What is the largest organ of the human body?',                                            'The skin'),
  (400,  'What gas makes up approximately 78% of Earth''s atmosphere?',                             'Nitrogen'),
  (400,  'How many chambers does the human heart have?',                                            'Four'),
  (400,  'What is the powerhouse of the cell?',                                                     'The mitochondria'),
  (400,  'What is the approximate speed of light?',                                                 'Approximately 300,000 km/s'),
  (400,  'What element is needed for combustion (fire) to occur?',                                  'Oxygen'),
  (400,  'What is the process by which plants make food using sunlight?',                           'Photosynthesis'),
  (600,  'Which organ in the human body produces insulin?',                                         'The pancreas'),
  (600,  'What is the process called when a liquid turns into a gas?',                              'Evaporation (vaporization)'),
  (600,  'What does Newton''s Third Law of Motion state?',                                          'For every action there is an equal and opposite reaction'),
  (600,  'What element has the chemical symbol Fe?',                                                'Iron'),
  (600,  'What type of rock is formed when molten lava cools and solidifies?',                      'Igneous rock'),
  (600,  'How many chromosomes does a typical human cell contain?',                                 '46'),
  (600,  'What is the scientific name for table salt?',                                             'Sodium chloride (NaCl)'),
  (600,  'What is the pH value of a neutral solution?',                                             'Seven'),
  (800,  'What is the name of the process by which a solid turns directly into a gas without becoming liquid?', 'Sublimation'),
  (800,  'What is the SI unit of electrical resistance?',                                           'Ohm (Ω)'),
  (800,  'What particle in the nucleus of an atom has no electrical charge?',                       'Neutron'),
  (800,  'What is the name of the process cells use to break down glucose and produce energy?',     'Cellular respiration'),
  (800,  'What phenomenon describes the apparent change in frequency of a wave as its source moves?', 'The Doppler effect'),
  (800,  'What is Avogadro''s number?',                                                             '6.022 × 10²³'),
  (800,  'What is the study of fossils called?',                                                    'Paleontology'),
  (800,  'What is the name for an atom that has gained or lost electrons?',                         'An ion'),
  (1000, 'What is the atomic number of carbon?',                                                    'Six'),
  (1000, 'What is the Heisenberg Uncertainty Principle?',                                           'You cannot simultaneously know both the exact position and exact momentum of a particle'),
  (1000, 'What phenomenon causes a straw to appear bent in a glass of water?',                      'Refraction'),
  (1000, 'What protein carries oxygen in red blood cells?',                                         'Hemoglobin'),
  (1000, 'In DNA, which base pairs with adenine?',                                                  'Thymine'),
  (1000, 'What is the name of the boundary between Earth''s mantle and outer core?',                'The Gutenberg discontinuity'),
  (1000, 'What does the Second Law of Thermodynamics state?',                                       'The entropy of a closed system tends to increase over time'),
  (1000, 'Which element has the highest melting point of all known elements?',                      'Tungsten (W), at approximately 3,422°C'),
  (1200, 'What is the half-life of Carbon-14, used in radiocarbon dating?',                         'Approximately 5,730 years'),
  (1200, 'What quantum effect allows particles to pass through barriers they classically could not?', 'Quantum tunneling'),
  (1200, 'What enzyme unwinds the DNA double helix during replication?',                            'Helicase'),
  (1200, 'What is Planck''s constant (approximate value)?',                                         '6.626 × 10⁻³⁴ joule-seconds'),
  (1200, 'What law states that the entropy of a perfect crystal at absolute zero is exactly zero?',  'The Third Law of Thermodynamics'),
  (1200, 'What is the name of the point inside a black hole where density becomes infinite?',       'The singularity'),
  (1200, 'What is the difference between a sigma bond and a pi bond?',                              'Sigma bonds form by head-on orbital overlap; pi bonds form by side-to-side orbital overlap'),
  (1200, 'What is the P vs NP problem in computer science?',                                        'Whether every problem whose solution can be quickly verified can also be quickly solved')
) AS q(pts, q_en, a_en)
WHERE c.name_en = 'Science';

-- 3. HISTORY (50 questions)
INSERT INTO questions (category_id, points, question_en, answer_en, question_ar, answer_ar)
SELECT c.id, q.pts, q.q_en, q.a_en, '', ''
FROM categories c
CROSS JOIN (VALUES
  (200,  'Who was the first President of the United States?',                                       'George Washington'),
  (200,  'In which century did World War II take place?',                                           'The 20th century (1939–1945)'),
  (200,  'Which ancient civilization built the Pyramids of Giza?',                                  'The ancient Egyptians'),
  (200,  'Who was the primary author of the Declaration of Independence?',                          'Thomas Jefferson'),
  (200,  'What war was fought between the North and South of the United States?',                   'The American Civil War'),
  (200,  'Which empire was ruled by Julius Caesar?',                                                'The Roman Empire'),
  (200,  'What country did Christopher Columbus sail from when he discovered the Americas?',        'Spain'),
  (200,  'In which continent is the country of Egypt located?',                                     'Africa'),
  (200,  'What wall separated East and West Germany during the Cold War?',                          'The Berlin Wall'),
  (400,  'In what year did World War I begin?',                                                     '1914'),
  (400,  'Who was the first man to walk on the Moon?',                                              'Neil Armstrong'),
  (400,  'In what year did the Berlin Wall fall?',                                                  '1989'),
  (400,  'Who was the leader of Germany during World War II?',                                      'Adolf Hitler'),
  (400,  'What was the name of the ship that sank on its maiden voyage in 1912?',                   'The Titanic'),
  (400,  'Who was the first female Prime Minister of the United Kingdom?',                          'Margaret Thatcher'),
  (400,  'What ancient document signed in 1215 limited the power of the English king?',             'The Magna Carta'),
  (400,  'In what city were the first modern Olympic Games (1896) held?',                           'Athens, Greece'),
  (400,  'In what year did India gain independence from British rule?',                              '1947'),
  (600,  'What was the name of the first artificial satellite launched into space?',                 'Sputnik 1'),
  (600,  'Who was the leader of the Soviet Union during the Cuban Missile Crisis?',                  'Nikita Khrushchev'),
  (600,  'In what year was the United Nations founded?',                                            '1945'),
  (600,  'What ancient trade route connected China to the Mediterranean world?',                     'The Silk Road'),
  (600,  'What event in 1929 triggered the Great Depression?',                                      'The Wall Street Crash (Black Tuesday)'),
  (600,  'Who led the Cuban Revolution in 1959?',                                                   'Fidel Castro'),
  (600,  'Which Egyptian pharaoh is most associated with the construction of the Great Pyramid?',    'Khufu (Cheops)'),
  (600,  'In what year was the French Revolution?',                                                 '1789'),
  (800,  'In what year did the Byzantine Empire fall to the Ottoman Turks?',                        '1453'),
  (800,  'What was the name of the treaty that officially ended World War I?',                      'The Treaty of Versailles'),
  (800,  'What was the code name for the Allied D-Day invasion of Normandy in 1944?',               'Operation Overlord'),
  (800,  'Which empire was the largest contiguous land empire in history?',                         'The Mongol Empire'),
  (800,  'Who was the first Roman Emperor?',                                                        'Augustus (Octavian)'),
  (800,  'What was the name of the Soviet nuclear reactor that exploded in 1986?',                  'Chernobyl'),
  (800,  'In what year did the apartheid regime officially end in South Africa?',                   '1994'),
  (800,  'What battle in 1066 resulted in the Norman conquest of England?',                         'The Battle of Hastings'),
  (1000, 'What war was fought between Athens and Sparta from 431–404 BC?',                         'The Peloponnesian War'),
  (1000, 'Who was the first Secretary-General of the United Nations?',                              'Trygve Lie (Norway)'),
  (1000, 'What was the name of the pact signed between Nazi Germany and the Soviet Union in 1939?', 'The Molotov-Ribbentrop Pact'),
  (1000, 'Who was the Ottoman Sultan who conquered Constantinople in 1453?',                        'Mehmed II (Mehmed the Conqueror)'),
  (1000, 'What empire was founded by Cyrus the Great around 550 BC?',                              'The Achaemenid (Persian) Empire'),
  (1000, 'In what year did the Russian Revolution overthrow Tsar Nicholas II?',                     '1917'),
  (1000, 'What was the name of the ship that carried the Pilgrims to Plymouth in 1620?',           'The Mayflower'),
  (1000, 'What treaty ended the Thirty Years'' War in 1648?',                                       'The Peace of Westphalia'),
  (1200, 'What was the name of the ancient Egyptian chancellor who built the Step Pyramid?',        'Imhotep'),
  (1200, 'In what year did the Ming Dynasty fall and the Qing Dynasty begin in China?',            '1644'),
  (1200, 'Who was the Carthaginian general who crossed the Alps with war elephants to attack Rome?', 'Hannibal Barca'),
  (1200, 'Which Roman Emperor issued the Edict of Milan and converted the empire to Christianity?', 'Constantine the Great'),
  (1200, 'What was Lenin''s economic policy introduced in 1921 that allowed limited private enterprise?', 'The New Economic Policy (NEP)'),
  (1200, 'In what year was the Battle of Marathon fought between Athens and Persia?',               '490 BC'),
  (1200, 'What was the name of the interwar international organization that preceded the United Nations?', 'The League of Nations'),
  (1200, 'Who led the Mongol conquest of China and founded the Yuan Dynasty?',                     'Kublai Khan')
) AS q(pts, q_en, a_en)
WHERE c.name_en = 'History';

-- 4. GEOGRAPHY (50 questions)
INSERT INTO questions (category_id, points, question_en, answer_en, question_ar, answer_ar)
SELECT c.id, q.pts, q.q_en, q.a_en, '', ''
FROM categories c
CROSS JOIN (VALUES
  (200,  'What is the capital city of France?',                                                     'Paris'),
  (200,  'What is the largest ocean in the world?',                                                 'The Pacific Ocean'),
  (200,  'On which continent is the Amazon rainforest located?',                                    'South America'),
  (200,  'What is the capital of the United Kingdom?',                                              'London'),
  (200,  'How many continents are there on Earth?',                                                 'Seven'),
  (200,  'What is the tallest mountain in the world?',                                              'Mount Everest'),
  (200,  'What is the longest river in the world?',                                                 'The Nile'),
  (200,  'What is the smallest continent by area?',                                                 'Australia'),
  (200,  'What is the capital city of Japan?',                                                      'Tokyo'),
  (400,  'What is the largest continent by area?',                                                  'Asia'),
  (400,  'What country has the most natural lakes in the world?',                                   'Canada'),
  (400,  'What two continents does Russia span?',                                                   'Europe and Asia'),
  (400,  'What is the capital city of Australia?',                                                  'Canberra'),
  (400,  'What ocean lies between Europe and North America?',                                       'The Atlantic Ocean'),
  (400,  'What is the name of the longest mountain range in the world?',                            'The Andes'),
  (400,  'What country is most associated with the Nile River?',                                    'Egypt'),
  (400,  'What is the capital of Brazil?',                                                          'Brasília'),
  (400,  'On which continent is the Sahara Desert located?',                                        'Africa'),
  (600,  'What is the name of the world''s largest hot desert?',                                    'The Sahara Desert'),
  (600,  'What is the capital city of Kazakhstan?',                                                 'Astana (formerly Nur-Sultan)'),
  (600,  'What country shares the longest land border with the United States?',                     'Canada'),
  (600,  'What is the name of the sea between Europe and Africa?',                                  'The Mediterranean Sea'),
  (600,  'What is the approximate area of Russia in square kilometres?',                            'Approximately 17.1 million km²'),
  (600,  'What is a strait in geography?',                                                          'A narrow body of water connecting two larger bodies of water'),
  (600,  'Which country has the largest population in the world (as of 2024)?',                     'India'),
  (600,  'On which continent is Argentina located?',                                                'South America'),
  (800,  'Through how many countries does the Danube River flow?',                                  'Ten countries'),
  (800,  'What is the deepest lake in the world?',                                                  'Lake Baikal (Russia)'),
  (800,  'What forms the geographic boundary between Europe and Asia?',                             'The Ural Mountains (and Ural River)'),
  (800,  'Which country has the most time zones including overseas territories?',                   'France (12 time zones)'),
  (800,  'What is the name of the world''s largest island (excluding continents)?',                 'Greenland'),
  (800,  'In which country is the Atacama Desert, the driest non-polar desert, located?',          'Chile'),
  (800,  'What is the name of the only sea with no land boundaries?',                               'The Sargasso Sea'),
  (800,  'What is an isthmus?',                                                                     'A narrow strip of land connecting two larger landmasses'),
  (1000, 'What is the capital city of Myanmar (Burma)?',                                            'Naypyidaw'),
  (1000, 'What is the geographic term for two tectonic plates moving apart?',                       'A divergent plate boundary'),
  (1000, 'What is the approximate length of the Amazon River in kilometres?',                      'Approximately 6,400 km'),
  (1000, 'Which country is completely surrounded by just one other country?',                       'Lesotho (surrounded by South Africa)'),
  (1000, 'What is the Coriolis effect?',                                                            'The deflection of winds/currents caused by Earth''s rotation — rightward in the Northern Hemisphere'),
  (1000, 'What is the name of the world''s highest navigable lake?',                               'Lake Titicaca (Bolivia/Peru)'),
  (1000, 'What is thermohaline circulation?',                                                       'The large-scale ocean circulation driven by temperature and salinity differences (the ocean conveyor belt)'),
  (1000, 'What is a tripoint (trijunction) in geography?',                                          'The point where three country borders meet'),
  (1200, 'What is the approximate elevation of the Dead Sea below sea level?',                      'Approximately 430 metres below sea level'),
  (1200, 'What is the capital of the Federated States of Micronesia?',                             'Palikir'),
  (1200, 'What is the name of the underwater mountain range running the length of the Atlantic?',  'The Mid-Atlantic Ridge'),
  (1200, 'What country does Socotra Island — known for unique biodiversity — belong to?',          'Yemen'),
  (1200, 'What is alluviation (alluvial deposition)?',                                              'The process by which rivers deposit sediment creating fertile floodplains'),
  (1200, 'What geological process created Norway''s fjords?',                                       'Glacially carved valleys (glacial troughs) subsequently flooded by the sea'),
  (1200, 'What Chinese region has the Mekong, Salween, and Yangtze running in parallel deep gorges?', 'The Three Parallel Rivers region (Yunnan, China)'),
  (1200, 'What is the approximate depth of the Mariana Trench''s Challenger Deep?',                'Approximately 11 km (10,994 metres)')
) AS q(pts, q_en, a_en)
WHERE c.name_en = 'Geography';

-- 5. SPORTS (50 questions)
INSERT INTO questions (category_id, points, question_en, answer_en, question_ar, answer_ar)
SELECT c.id, q.pts, q.q_en, q.a_en, '', ''
FROM categories c
CROSS JOIN (VALUES
  (200,  'How many players are on a basketball team on the court at one time?',                     'Five'),
  (200,  'In which sport do players use a racket on a grass or clay court?',                        'Tennis'),
  (200,  'How many players are on a soccer (football) team on the field?',                         'Eleven'),
  (200,  'How many innings are in a standard baseball game?',                                      'Nine'),
  (200,  'In which sport would you perform a slam dunk?',                                           'Basketball'),
  (200,  'What sport uses a puck instead of a ball?',                                              'Ice hockey'),
  (200,  'How many players are on each side of the net in volleyball?',                             'Six'),
  (200,  'What is the objective of golf?',                                                          'To hit a ball into a series of holes in as few strokes as possible'),
  (200,  'How many gold medals can an athlete win per event at one Olympic Games?',                 'One'),
  (400,  'In which country was the first FIFA World Cup held?',                                    'Uruguay (1930)'),
  (400,  'How many holes are in a standard round of golf?',                                        'Eighteen'),
  (400,  'In what year were the first modern Olympic Games held?',                                  '1896 (Athens, Greece)'),
  (400,  'How many points is a touchdown worth in American football?',                              'Six'),
  (400,  'What sport is played at Wimbledon?',                                                     'Tennis'),
  (400,  'How many players are on each side in a rugby union match?',                              'Fifteen'),
  (400,  'What does LBW stand for in cricket?',                                                    'Leg Before Wicket'),
  (400,  'How long does a standard boxing round last?',                                            'Three minutes'),
  (400,  'Which country has won the most FIFA World Cup titles?',                                   'Brazil (five times)'),
  (600,  'What is the maximum number of sets in a men''s Grand Slam tennis singles match?',        'Five sets'),
  (600,  'In golf, what is one stroke under par on a hole called?',                                'Birdie'),
  (600,  'How many events make up the decathlon?',                                                 'Ten events'),
  (600,  'What is the distance of a marathon in kilometres?',                                     '42.195 km'),
  (600,  'In which city were the 2016 Summer Olympics held?',                                     'Rio de Janeiro, Brazil'),
  (600,  'In Olympic weightlifting, what are the two lifts performed?',                             'Snatch and Clean-and-Jerk'),
  (600,  'What is the name of the international governing body of football (soccer)?',              'FIFA'),
  (600,  'What is the highest possible break in snooker?',                                         '147'),
  (800,  'What is the official weight of the men''s Olympic shot put in kilograms?',               '7.26 kg'),
  (800,  'What is a perfect game in ten-pin bowling?',                                             '300 points — achieved by 12 consecutive strikes'),
  (800,  'What is the butterfly stroke in swimming?',                                              'A stroke where both arms move forward simultaneously out of the water while the legs perform a dolphin kick'),
  (800,  'What is the Tour de France?',                                                            'The most prestigious annual cycling race, spanning roughly 3,500 km across France'),
  (800,  'How many points is a Try worth in rugby union?',                                         'Five points'),
  (800,  'In chess, which piece can only move diagonally?',                                        'The bishop'),
  (800,  'What does winning the Grand Slam mean in tennis?',                                       'Winning all four major tournaments in one year: Australian Open, French Open, Wimbledon, and US Open'),
  (800,  'What is the ancient Greek sprint race run at the original Olympics called?',             'The stadion race (a sprint of roughly 192 metres)'),
  (1000, 'What is Usain Bolt''s 100m world record time set in 2009?',                              '9.58 seconds'),
  (1000, 'What is the Fosbury Flop?',                                                              'A high jump technique going over the bar headfirst and back-first, pioneered by Dick Fosbury at the 1968 Olympics'),
  (1000, 'What is the Duckworth-Lewis-Stern method used for in cricket?',                          'Calculating revised target scores in rain-affected limited overs matches'),
  (1000, 'In which year did South Africa host and win the Rugby World Cup?',                       '1995'),
  (1000, 'What is the minimum score needed to win a set in table tennis?',                         '11 points (with at least a 2-point lead)'),
  (1000, 'In chess, what is stalemate?',                                                           'When a player has no legal moves but is not in check — the game ends as a draw'),
  (1000, 'What sequence of strokes is swum in the individual medley?',                             'Butterfly, Backstroke, Breaststroke, Freestyle'),
  (1000, 'What penalty is given in soccer when a goalkeeper handles a deliberate back-pass from a teammate?', 'An indirect free kick'),
  (1200, 'What is the exact distance of a marathon in miles?',                                     '26 miles 385 yards (approximately 26.22 miles)'),
  (1200, 'What does the fencing term touché mean?',                                                'A hit scored on the opponent — an acknowledgment that a touch was made'),
  (1200, 'In Olympic archery, what is the standard shooting distance?',                            'Seventy metres'),
  (1200, 'What was the nationality of the first non-British F1 World Champion?',                   'Argentine (Juan Manuel Fangio, 1951)'),
  (1200, 'What was the official match ball at the 2022 FIFA World Cup in Qatar?',                  'Al Rihla (by Adidas)'),
  (1200, 'In rowing, what is the difference between sculling and sweep rowing?',                   'In sculling each rower uses two oars; in sweep rowing each rower uses one oar'),
  (1200, 'Who is the legendary Finnish runner nicknamed the Flying Finn who won 9 Olympic gold medals?', 'Paavo Nurmi'),
  (1200, 'In curling, what is the circular target at the end of the sheet called?',               'The house')
) AS q(pts, q_en, a_en)
WHERE c.name_en = 'Sports';

-- 6. MOVIES & TV (50 questions)
INSERT INTO questions (category_id, points, question_en, answer_en, question_ar, answer_ar)
SELECT c.id, q.pts, q.q_en, q.a_en, '', ''
FROM categories c
CROSS JOIN (VALUES
  (200,  'Which animated Disney film features a young lion named Simba?',                           'The Lion King'),
  (200,  'Who played Iron Man in the Marvel Cinematic Universe?',                                  'Robert Downey Jr.'),
  (200,  'What fictional school does Harry Potter attend?',                                         'Hogwarts School of Witchcraft and Wizardry'),
  (200,  'What TV show features a chemistry teacher who secretly becomes a drug kingpin?',          'Breaking Bad'),
  (200,  'What animated film features a clownfish searching for his son Nemo?',                     'Finding Nemo'),
  (200,  'Who played Jack Dawson in the 1997 film Titanic?',                                       'Leonardo DiCaprio'),
  (200,  'What is the name of the cowboy toy in Toy Story?',                                       'Woody'),
  (200,  'What streaming platform produced Stranger Things?',                                      'Netflix'),
  (200,  'In what film does a boy say the line "I see dead people"?',                              'The Sixth Sense'),
  (400,  'Who directed The Dark Knight (2008) and Inception (2010)?',                              'Christopher Nolan'),
  (400,  'In what year was the original Star Wars film (Episode IV) released?',                    '1977'),
  (400,  'What is the name of the fictional African country in Black Panther?',                    'Wakanda'),
  (400,  'Who played Jon Snow in Game of Thrones?',                                               'Kit Harington'),
  (400,  'Who played Katniss Everdeen in The Hunger Games films?',                                 'Jennifer Lawrence'),
  (400,  'Who directed the Lord of the Rings trilogy?',                                            'Peter Jackson'),
  (400,  'What 2019 Korean film won the Academy Award for Best Picture?',                          'Parasite'),
  (400,  'What TV sitcom is set in a bar in Boston?',                                              'Cheers'),
  (400,  'Who composed the iconic music for the Star Wars series?',                                'John Williams'),
  (600,  'Who directed the 1968 science fiction epic 2001: A Space Odyssey?',                      'Stanley Kubrick'),
  (600,  'What character does Marlon Brando play in The Godfather (1972)?',                        'Vito Corleone'),
  (600,  'What film features the line "I''m going to make him an offer he can''t refuse"?',       'The Godfather (1972)'),
  (600,  'In which city is the TV show Friends set?',                                              'New York City'),
  (600,  'What 1994 film stars Tom Hanks as a kind-hearted man sitting on a park bench?',          'Forrest Gump'),
  (600,  'What was the first feature-length animated film produced by Walt Disney?',               'Snow White and the Seven Dwarfs (1937)'),
  (600,  'Who plays Sherlock Holmes in the BBC television series Sherlock?',                       'Benedict Cumberbatch'),
  (600,  'What Alfred Hitchcock film features a shocking murder in a shower at the Bates Motel?',  'Psycho (1960)'),
  (800,  'In what year was the first Emmy Award ceremony held?',                                   '1949'),
  (800,  'Who played Hannibal Lecter in The Silence of the Lambs?',                               'Anthony Hopkins'),
  (800,  'What character did Bryan Cranston play in Breaking Bad?',                                'Walter White'),
  (800,  'What film studio produced Shrek and Madagascar?',                                        'DreamWorks Animation'),
  (800,  'Who directed Schindler''s List (1993)?',                                                 'Steven Spielberg'),
  (800,  'In what year did The Sopranos premiere on HBO?',                                         '1999'),
  (800,  'What 2014 film by Alejandro González Iñárritu won the Academy Award for Best Picture?', 'Birdman'),
  (800,  'In what film does Jack Nicholson deliver the line "Here''s Johnny!"?',                   'The Shining (1980)'),
  (1000, 'Who plays the Joker in the 2019 standalone film Joker?',                                'Joaquin Phoenix'),
  (1000, 'What French cinematic New Wave movement emerged in the late 1950s–60s?',                 'Nouvelle Vague'),
  (1000, 'What is the name of the fictional language spoken by the Na''vi in Avatar?',             'Na''vi'),
  (1000, 'Who directed Apocalypse Now (1979)?',                                                    'Francis Ford Coppola'),
  (1000, 'What camera technique zooms in while the dolly moves back, creating a disorienting effect?', 'Dolly zoom (Hitchcock zoom or Vertigo effect)'),
  (1000, 'Who won the Best Actor Oscar for his role in Philadelphia (1993)?',                      'Tom Hanks'),
  (1000, 'What 1985 Terry Gilliam film depicts a dystopian bureaucratic future?',                  'Brazil'),
  (1000, 'What is the Bechdel test in film?',                                                      'A test checking whether a film has at least two named women who talk to each other about something other than a man'),
  (1200, 'What Japanese animation studio produced Spirited Away and My Neighbor Totoro?',          'Studio Ghibli'),
  (1200, 'What 1922 silent horror film is an unauthorised adaptation of Dracula?',                 'Nosferatu (Eine Symphonie des Grauens)'),
  (1200, 'What is the Kuleshov effect in filmmaking?',                                             'Meaning changes based on what shot precedes another — the audience reads emotion into a neutral face based on context'),
  (1200, 'Who directed the 1927 German Expressionist film Metropolis?',                            'Fritz Lang'),
  (1200, 'Who composed the theme music for the TV series Twin Peaks?',                             'Angelo Badalamenti'),
  (1200, 'In which film does Orson Welles play Charles Foster Kane?',                              'Citizen Kane (1941)'),
  (1200, 'What is the 180-degree rule in filmmaking?',                                             'The camera should stay on one side of an imaginary line between characters to maintain spatial consistency'),
  (1200, 'What is mise-en-scène in film theory?',                                                  'The arrangement of everything within the film frame — sets, lighting, actors, props — used as expressive tools')
) AS q(pts, q_en, a_en)
WHERE c.name_en = 'Movies & TV';

-- 7. MUSIC (50 questions)
INSERT INTO questions (category_id, points, question_en, answer_en, question_ar, answer_ar)
SELECT c.id, q.pts, q.q_en, q.a_en, '', ''
FROM categories c
CROSS JOIN (VALUES
  (200,  'How many strings does a standard guitar have?',                                           'Six strings'),
  (200,  'Which band recorded Bohemian Rhapsody?',                                                  'Queen'),
  (200,  'How many notes are in a standard musical octave?',                                        'Eight'),
  (200,  'What band was Michael Jackson part of before going solo?',                                'The Jackson 5'),
  (200,  'Who is known as the Queen of Pop?',                                                       'Madonna'),
  (200,  'What does the Italian musical term "piano" (dynamic marking) mean?',                      'Soft / quiet'),
  (200,  'How many musicians are in a quartet?',                                                    'Four'),
  (200,  'What music streaming platform was founded in Sweden in 2006?',                            'Spotify'),
  (200,  'What instrument does a DJ use to mix music?',                                             'Turntable (or DJ mixer / controller)'),
  (400,  'In what year did Michael Jackson release the album Thriller?',                            '1982'),
  (400,  'Which British band sang Hey Jude and Let It Be?',                                         'The Beatles'),
  (400,  'What is the musical term for the speed at which a piece is played?',                      'Tempo'),
  (400,  'Who is known as the King of Rock and Roll?',                                              'Elvis Presley'),
  (400,  'What is the name of the highest-pitched voice in a choir?',                               'Soprano'),
  (400,  'Who sang Rolling in the Deep and Hello?',                                                 'Adele'),
  (400,  'What band featured Mick Jagger and Keith Richards?',                                      'The Rolling Stones'),
  (400,  'What genre of music originated in New Orleans combining blues, ragtime, and brass?',      'Jazz'),
  (400,  'What music award is the industry equivalent of the Oscar?',                               'The Grammy Award'),
  (600,  'Who composed the opera The Magic Flute (Die Zauberflöte)?',                               'Wolfgang Amadeus Mozart'),
  (600,  'What is the time signature in music?',                                                    'The indication at the start of a piece showing how many beats are in each measure'),
  (600,  'What is a musical composition written for a full orchestra called?',                      'A symphony'),
  (600,  'What is a cappella music?',                                                               'Vocal music performed without instrumental accompaniment'),
  (600,  'What is a musical arpeggio?',                                                             'A chord where notes are played in rapid succession rather than simultaneously'),
  (600,  'What is a saxophone classified as?',                                                      'A woodwind instrument (with a single reed, made of brass)'),
  (600,  'What famous composer became progressively deaf yet continued composing masterpieces?',    'Ludwig van Beethoven'),
  (600,  'What is counterpoint in music?',                                                          'The technique of combining two or more independent melodic lines simultaneously'),
  (800,  'What is the name of the scale that includes all 12 half-steps within one octave?',       'The chromatic scale'),
  (800,  'What is a musical triplet?',                                                              'Three notes played in the time normally occupied by two notes of the same value'),
  (800,  'What generally distinguishes a major key from a minor key?',                              'Major keys sound brighter/happier; minor keys sound darker/sadder due to different interval patterns'),
  (800,  'What is a fugue in music?',                                                               'A polyphonic composition where a short melody (subject) is introduced then imitated across multiple voices at different pitches'),
  (800,  'Who composed The Four Seasons?',                                                          'Antonio Vivaldi'),
  (800,  'What is spiccato in string playing?',                                                     'A bowing technique where the bow bounces lightly off the strings'),
  (800,  'What is the blues scale?',                                                                'A pentatonic minor scale with an added flattened fifth (the blue note)'),
  (800,  'Who composed The Goldberg Variations?',                                                   'Johann Sebastian Bach'),
  (1000, 'What is the 12-tone composition technique developed by Arnold Schoenberg?',               'Serialism (twelve-tone technique / dodecaphony)'),
  (1000, 'Who composed The Rite of Spring (1913) whose premiere caused a near-riot?',              'Igor Stravinsky'),
  (1000, 'What musical term describes a gradual decrease in tempo?',                                'Rallentando (or ritardando)'),
  (1000, 'What is a cadenza in a concerto?',                                                        'A solo passage, often improvised, near the end of a movement where the soloist displays virtuosity'),
  (1000, 'What is sonata form in classical music?',                                                 'A three-part structure: exposition, development, and recapitulation'),
  (1000, 'Who composed Don Giovanni?',                                                              'Wolfgang Amadeus Mozart'),
  (1000, 'What is the passaggio in singing?',                                                       'The "break" or transition between chest voice and head voice / falsetto'),
  (1000, 'In what year did Beethoven complete his Ninth Symphony?',                                 '1824'),
  (1200, 'What is the difference between equal temperament and just intonation?',                   'Equal temperament uses 12 equal half-steps per octave; just intonation uses pure whole-number frequency ratios'),
  (1200, 'What section of a symphony in sonata form develops and transforms the opening themes?',   'The development section'),
  (1200, 'What is the mathematical ratio of a perfect fifth in just intonation?',                   '3:2'),
  (1200, 'What musical form has two or more independent melodic lines played simultaneously?',      'Polyphony (counterpoint)'),
  (1200, 'What is Shostakovich''s Symphony No. 7 nicknamed?',                                       'The Leningrad Symphony'),
  (1200, 'What is the Mannheim crescendo?',                                                         'A controlled gradual crescendo technique developed by the 18th-century Mannheim orchestra'),
  (1200, 'What is serialism in music composition?',                                                 'A technique using an ordered series of pitches ensuring all appear before any repeats'),
  (1200, 'What is the interval where one note is exactly double the frequency of another?',         'An octave')
) AS q(pts, q_en, a_en)
WHERE c.name_en = 'Music';

-- 8. TECHNOLOGY (50 questions)
INSERT INTO questions (category_id, points, question_en, answer_en, question_ar, answer_ar)
SELECT c.id, q.pts, q.q_en, q.a_en, '', ''
FROM categories c
CROSS JOIN (VALUES
  (200,  'What does CPU stand for?',                                                                'Central Processing Unit'),
  (200,  'What company makes the iPhone?',                                                         'Apple'),
  (200,  'What does www stand for in a web address?',                                              'World Wide Web'),
  (200,  'What keyboard shortcut undoes an action on most computers?',                             'Ctrl+Z (Cmd+Z on Mac)'),
  (200,  'What is the name of Google''s mobile operating system?',                                  'Android'),
  (200,  'What does USB stand for?',                                                               'Universal Serial Bus'),
  (200,  'What is the world''s most visited search engine?',                                        'Google'),
  (200,  'What social media platform is known for short videos?',                                  'TikTok'),
  (200,  'What does Wi-Fi allow you to do?',                                                        'Connect to the internet wirelessly'),
  (400,  'Who co-founded Apple Inc. alongside Steve Jobs?',                                        'Steve Wozniak'),
  (400,  'In what year did Tim Berners-Lee propose the World Wide Web?',                           '1989'),
  (400,  'What programming language was created by Guido van Rossum?',                             'Python'),
  (400,  'What does RAM stand for?',                                                               'Random Access Memory'),
  (400,  'What does HTML stand for?',                                                              'Hypertext Markup Language'),
  (400,  'What company owns Instagram and WhatsApp?',                                              'Meta (formerly Facebook)'),
  (400,  'What is Apple''s desktop operating system called?',                                       'macOS'),
  (400,  'What is a firewall in computing?',                                                        'A security system that monitors and controls network traffic based on security rules'),
  (400,  'What does PDF stand for?',                                                               'Portable Document Format'),
  (600,  'What encryption standard replaced DES as the US federal standard in 2001?',              'AES (Advanced Encryption Standard)'),
  (600,  'What does HTTP stand for?',                                                              'Hypertext Transfer Protocol'),
  (600,  'What is Moore''s Law?',                                                                   'The observation that the number of transistors on a microchip doubles approximately every two years'),
  (600,  'What protocol is used to send email?',                                                   'SMTP (Simple Mail Transfer Protocol)'),
  (600,  'What is the difference between RAM and ROM?',                                            'RAM is volatile (loses data when off); ROM is non-volatile (retains data permanently)'),
  (600,  'What programming paradigm uses objects containing data and methods?',                    'Object-Oriented Programming (OOP)'),
  (600,  'Who created the Linux kernel?',                                                          'Linus Torvalds'),
  (600,  'What language is primarily used for web page styling?',                                  'CSS (Cascading Style Sheets)'),
  (800,  'What is the main difference between IPv4 and IPv6?',                                     'IPv4 uses 32-bit addresses (~4.3 billion); IPv6 uses 128-bit addresses (vastly larger address space)'),
  (800,  'What does a DNS server do?',                                                             'Translates domain names (like google.com) into IP addresses'),
  (800,  'What is the CAP theorem in distributed systems?',                                        'A system can only simultaneously guarantee two of: Consistency, Availability, Partition tolerance'),
  (800,  'What is the difference between a compiler and an interpreter?',                          'A compiler translates all code at once; an interpreter executes code line by line'),
  (800,  'In what year was the first iPhone released?',                                            '2007'),
  (800,  'Who founded the Ethereum blockchain?',                                                   'Vitalik Buterin'),
  (800,  'What is machine learning?',                                                              'A branch of AI where systems learn from data to improve without being explicitly programmed'),
  (800,  'What does API stand for and what does it do?',                                           'Application Programming Interface — defines rules for how software applications communicate'),
  (1000, 'What is the Big O notation for binary search?',                                         'O(log n)'),
  (1000, 'What is two''s complement used for in computing?',                                        'Representing both positive and negative integers in binary using a fixed number of bits'),
  (1000, 'What is the halting problem in computer science?',                                       'The undecidable problem of determining whether a given program will halt or run forever'),
  (1000, 'What protocol does HTTPS use to secure web communication?',                             'TLS (Transport Layer Security), formerly SSL'),
  (1000, 'What is a race condition in concurrent programming?',                                    'A bug where the outcome depends on the unpredictable timing or order of concurrent operations'),
  (1000, 'What is Docker used for in software development?',                                       'Running applications in isolated containers ensuring consistent behaviour across environments'),
  (1000, 'What is SQL?',                                                                           'Structured Query Language — used to manage and query relational databases'),
  (1000, 'What is the difference between deep learning and traditional machine learning?',         'Deep learning uses multi-layered neural networks; traditional ML typically requires manual feature engineering'),
  (1200, 'What is the Church-Turing thesis?',                                                      'Any effectively computable function can be computed by a Turing machine — defining the limits of computation'),
  (1200, 'What is the Von Neumann architecture?',                                                  'A computer design where CPU, memory, and I/O share a bus, with program instructions and data in the same memory'),
  (1200, 'What is a man-in-the-middle (MITM) attack?',                                            'An attack where an adversary secretly intercepts and possibly alters communication between two parties'),
  (1200, 'What does the Nyquist-Shannon sampling theorem state?',                                  'A signal can be perfectly reconstructed if sampled at more than twice its highest frequency'),
  (1200, 'What is Kubernetes?',                                                                    'An open-source system for automating deployment, scaling, and management of containerised applications'),
  (1200, 'What is the P vs NP problem?',                                                          'Whether every problem whose solution can be quickly verified can also be quickly solved'),
  (1200, 'What is a zero-day vulnerability?',                                                      'A software flaw unknown to the vendor with no patch — exploitable immediately with zero days of warning'),
  (1200, 'What is the difference between symmetric and asymmetric encryption?',                    'Symmetric uses one shared key; asymmetric uses a public key to encrypt and a private key to decrypt')
) AS q(pts, q_en, a_en)
WHERE c.name_en = 'Technology';

-- 9. LITERATURE (50 questions)
INSERT INTO questions (category_id, points, question_en, answer_en, question_ar, answer_ar)
SELECT c.id, q.pts, q.q_en, q.a_en, '', ''
FROM categories c
CROSS JOIN (VALUES
  (200,  'Who wrote Romeo and Juliet?',                                                             'William Shakespeare'),
  (200,  'What is the name of the boy who never grows up in J.M. Barrie''s story?',               'Peter Pan'),
  (200,  'Who wrote Harry Potter and the Philosopher''s Stone?',                                    'J.K. Rowling'),
  (200,  'What is the name of the fictional detective who lives on Baker Street?',                  'Sherlock Holmes'),
  (200,  'In Alice''s Adventures in Wonderland, what does Alice follow down the rabbit hole?',     'A white rabbit'),
  (200,  'Who wrote the Diary of a Young Girl, a famous World War II memoir?',                     'Anne Frank'),
  (200,  'What novel begins with "It was the best of times, it was the worst of times"?',          'A Tale of Two Cities (by Charles Dickens)'),
  (200,  'What is the name of the orphan boy in Dickens'' novel who asks for more food?',          'Oliver Twist'),
  (200,  'What is the name of the hobbit protagonist in The Hobbit?',                               'Bilbo Baggins'),
  (400,  'In which novel does the mysterious character Jay Gatsby appear?',                         'The Great Gatsby (by F. Scott Fitzgerald)'),
  (400,  'Who wrote 1984 and Animal Farm?',                                                         'George Orwell'),
  (400,  'Who wrote Pride and Prejudice?',                                                          'Jane Austen'),
  (400,  'What is the opening line of Herman Melville''s Moby-Dick?',                               '"Call me Ishmael."'),
  (400,  'Who wrote Crime and Punishment?',                                                         'Fyodor Dostoevsky'),
  (400,  'What Harper Lee novel addresses racial injustice in the American South?',                 'To Kill a Mockingbird'),
  (400,  'Who wrote The Alchemist (O Alquimista)?',                                                 'Paulo Coelho'),
  (400,  'Who wrote The Chronicles of Narnia?',                                                     'C.S. Lewis'),
  (400,  'Who wrote Don Quixote, considered the first modern European novel?',                      'Miguel de Cervantes'),
  (600,  'What is the subtitle of Mary Shelley''s novel Frankenstein?',                             'The Modern Prometheus'),
  (600,  'Who wrote Paradise Lost?',                                                                'John Milton'),
  (600,  'In what language did Dante Alighieri originally write the Divine Comedy?',               'Italian (Tuscan dialect)'),
  (600,  'What James Joyce novel is considered one of the most complex works in English?',          'Ulysses'),
  (600,  'Who wrote The Metamorphosis (Die Verwandlung)?',                                          'Franz Kafka'),
  (600,  'What is the name of the dystopian society in Margaret Atwood''s The Handmaid''s Tale?',  'Gilead'),
  (600,  'What literary movement emphasised irrationality and the unconscious mind?',               'Surrealism'),
  (600,  'Who wrote Middlemarch, often called the greatest English novel?',                         'George Eliot (pen name of Mary Ann Evans)'),
  (800,  'What is the name of the narrator in Nabokov''s novel Lolita?',                           'Humbert Humbert'),
  (800,  'What is the stream of consciousness technique in literature?',                            'Capturing the continuous flow of a character''s thoughts and feelings in real time'),
  (800,  'What is the name of the tragic Danish prince in Shakespeare''s play?',                   'Hamlet'),
  (800,  'What Nobel Prize-winning Colombian author wrote One Hundred Years of Solitude?',         'Gabriel García Márquez'),
  (800,  'What is magical realism as a literary genre?',                                           'Fantastical or magical elements presented naturally within realistic settings, treated as ordinary'),
  (800,  'Who wrote The Brothers Karamazov?',                                                       'Fyodor Dostoevsky'),
  (800,  'What is an unreliable narrator?',                                                         'A narrator whose credibility is compromised, leaving the reader to question the accuracy of events'),
  (800,  'What Russian author wrote War and Peace and Anna Karenina?',                             'Leo Tolstoy'),
  (1000, 'What Homer epic poem tells of Odysseus''s journey home from Troy?',                       'The Odyssey'),
  (1000, 'Who wrote Thus Spoke Zarathustra (Also sprach Zarathustra)?',                            'Friedrich Nietzsche'),
  (1000, 'Who wrote The Sound and the Fury?',                                                       'William Faulkner'),
  (1000, 'What is a literary foil?',                                                                'A character who contrasts with the main character to highlight their traits'),
  (1000, 'What is a literary flashback (analepsis)?',                                               'A narrative device interrupting the story to show events that happened earlier'),
  (1000, 'What is ekphrasis in literature?',                                                        'A vivid literary description of a work of visual art'),
  (1000, 'Who wrote The Canterbury Tales?',                                                         'Geoffrey Chaucer'),
  (1000, 'What is the term for the tragic flaw in a hero that leads to their downfall?',           'Hamartia'),
  (1200, 'What Heian period Japanese work (around 1000 AD) is considered one of the world''s first novels?', 'The Tale of Genji (Genji Monogatari) by Murasaki Shikibu'),
  (1200, 'What is the difference between a simile and a metaphor?',                                'A simile compares using "like" or "as"; a metaphor states one thing IS another directly'),
  (1200, 'Who wrote The Waste Land (1922), a landmark of modernist poetry?',                       'T.S. Eliot'),
  (1200, 'What is Chekhov''s Gun as a narrative principle?',                                        'Every story element introduced must serve a purpose — if a gun appears in Act 1, it must fire by Act 3'),
  (1200, 'What Latin American literary movement in the 1960s–70s produced One Hundred Years of Solitude?', 'El Boom (the Latin American literary boom)'),
  (1200, 'What is "in medias res" as a narrative technique?',                                       'Beginning a story in the middle of the action rather than at the chronological beginning'),
  (1200, 'What is the ancient Sanskrit epic attributed to the sage Valmiki?',                       'The Ramayana'),
  (1200, 'Who wrote Absalom, Absalom! (1936), a novel about the decline of a Southern dynasty?',   'William Faulkner')
) AS q(pts, q_en, a_en)
WHERE c.name_en = 'Literature';

-- 10. ART (50 questions)
INSERT INTO questions (category_id, points, question_en, answer_en, question_ar, answer_ar)
SELECT c.id, q.pts, q.q_en, q.a_en, '', ''
FROM categories c
CROSS JOIN (VALUES
  (200,  'Who painted the Mona Lisa?',                                                             'Leonardo da Vinci'),
  (200,  'What are the three primary colours in traditional painting?',                            'Red, blue, and yellow'),
  (200,  'What museum in Paris houses the Mona Lisa?',                                             'The Louvre'),
  (200,  'Who painted the Sistine Chapel ceiling?',                                               'Michelangelo'),
  (200,  'What colour do you get by mixing red and blue?',                                        'Purple'),
  (200,  'What is the name of the art form that involves folding paper into shapes?',             'Origami'),
  (200,  'What tool does a painter use to apply paint to a canvas?',                              'A paintbrush'),
  (200,  'What is a self-portrait?',                                                              'A portrait of an artist made by the artist themselves'),
  (200,  'What colour do you get by mixing red and white?',                                       'Pink'),
  (400,  'Which Spanish artist co-founded the Cubist movement?',                                  'Pablo Picasso'),
  (400,  'In which century did the Italian Renaissance begin?',                                   'The 14th century (1300s)'),
  (400,  'Which Dutch Golden Age painter created Girl with a Pearl Earring?',                     'Johannes Vermeer'),
  (400,  'Who painted The Starry Night?',                                                         'Vincent van Gogh'),
  (400,  'Who sculpted the famous statue David?',                                                 'Michelangelo'),
  (400,  'What is the technique of painting on wet plaster called?',                              'Fresco'),
  (400,  'What art movement used bright non-naturalistic colours?',                               'Fauvism'),
  (400,  'What technique involves pasting various materials onto a surface to create art?',       'Collage'),
  (400,  'What is the term for the arrangement of visual elements within a work of art?',        'Composition'),
  (600,  'What is the term for applying paint so thickly it creates a textured 3D surface?',     'Impasto'),
  (600,  'Who sculpted The Thinker?',                                                             'Auguste Rodin'),
  (600,  'Who painted The Persistence of Memory with melting clocks?',                           'Salvador Dalí'),
  (600,  'What is Japanese ink wash painting called?',                                            'Sumi-e'),
  (600,  'What is pointillism?',                                                                  'A technique using tiny dots of pure colour placed side by side to form an image'),
  (600,  'What art movement used imagery from mass media and advertising?',                       'Pop Art'),
  (600,  'Who is known for painting large colourful flowers and New Mexico landscapes?',         'Georgia O''Keeffe'),
  (600,  'What is chiaroscuro in painting?',                                                      'The dramatic use of strong light-dark contrast to create depth and three-dimensionality'),
  (800,  'What does trompe-l''œil mean and what is it in art?',                                   'Literally "deceives the eye" — a painting technique creating a realistic 3D illusion on a flat surface'),
  (800,  'Who founded the Bauhaus school of art and design in 1919?',                            'Walter Gropius'),
  (800,  'What is the Golden Ratio and how is it used in art?',                                  'A ratio of ~1.618:1 found in nature and used to create visually harmonious proportions in art and architecture'),
  (800,  'What is lithography in printmaking?',                                                   'A printing technique using a flat surface treated to hold ink in certain areas, based on oil and water repulsion'),
  (800,  'Who painted American Gothic (1930)?',                                                   'Grant Wood'),
  (800,  'Who created the readymades concept using everyday objects as fine art?',                'Marcel Duchamp'),
  (800,  'Which French Impressionist is most famous for painting ballerina scenes?',             'Edgar Degas'),
  (800,  'What painting technique uses egg yolk as the binding medium?',                         'Egg tempera'),
  (1000, 'What is sfumato in Renaissance painting?',                                              'Leonardo da Vinci''s technique of blending colours and tones so smoothly there are no sharp outlines'),
  (1000, 'Who were the three great masters of the High Italian Renaissance?',                    'Leonardo da Vinci, Michelangelo, and Raphael'),
  (1000, 'What is the Japanese woodblock print art tradition called?',                           'Ukiyo-e (pictures of the floating world)'),
  (1000, 'What did the Dadaist art movement believe?',                                           'Traditional art was meaningless after WWI — they embraced irrationality, absurdity, and anti-aesthetics'),
  (1000, 'What is the difference between abstract and non-objective art?',                       'Abstract art distorts real subjects; non-objective art has no reference to the real world at all'),
  (1000, 'What is aesthetics as a branch of philosophy?',                                        'The philosophical study of beauty, art, and the nature of aesthetic experience and judgement'),
  (1000, 'What is encaustic painting?',                                                          'An ancient technique using pigments mixed with hot wax as the binding medium'),
  (1000, 'What Flemish master painted The Garden of Earthly Delights?',                          'Hieronymus Bosch'),
  (1200, 'What avant-garde movement was co-founded by Kandinsky, emphasising spiritual values in abstract art?', 'Der Blaue Reiter (The Blue Rider)'),
  (1200, 'What is grisaille in painting?',                                                        'A monochromatic painting technique executed entirely in shades of grey'),
  (1200, 'What is pentimento in art?',                                                            'Evidence of an earlier painting that becomes visible through outer paint layers as they age and become transparent'),
  (1200, 'What is Greenbergian formalism in art criticism?',                                     'Clement Greenberg''s theory championing abstraction and "pure" art forms, valuing medium specificity'),
  (1200, 'Who created action painting associated with Abstract Expressionism?',                  'Jackson Pollock (known for his drip painting technique)'),
  (1200, 'What painting medium uses a polymer emulsion as the binder?',                         'Acrylic paint'),
  (1200, 'What ancient Roman painting technique was preserved at Pompeii?',                      'Fresco (buon fresco — pigments applied to wet lime plaster)'),
  (1200, 'What is gesso in painting?',                                                            'A white primer coat applied to canvas or wood before painting, providing a suitable surface for paint adhesion')
) AS q(pts, q_en, a_en)
WHERE c.name_en = 'Art';

-- 11. FOOD & DRINK (50 questions)
INSERT INTO questions (category_id, points, question_en, answer_en, question_ar, answer_ar)
SELECT c.id, q.pts, q.q_en, q.a_en, '', ''
FROM categories c
CROSS JOIN (VALUES
  (200,  'What fruit is the main ingredient in guacamole?',                                        'Avocado'),
  (200,  'From which country does pizza originally come?',                                        'Italy'),
  (200,  'What is the main ingredient in bread?',                                                 'Flour (wheat)'),
  (200,  'What drink is made from fermented grapes?',                                             'Wine'),
  (200,  'What is the name of the Japanese dish of vinegared rice with seafood or vegetables?',   'Sushi'),
  (200,  'What is the most commonly drunk beverage in the world after water?',                    'Tea'),
  (200,  'What sweet condiment is made by bees?',                                                 'Honey'),
  (200,  'What drink is made by brewing roasted ground coffee beans?',                            'Coffee'),
  (200,  'What spice gives curry its yellow colour?',                                             'Turmeric'),
  (400,  'What is the Japanese alcoholic drink made from fermented rice?',                        'Sake'),
  (400,  'What country is famous for its Gouda and Edam cheeses?',                               'The Netherlands'),
  (400,  'What is the main ingredient in hummus?',                                                'Chickpeas (garbanzo beans)'),
  (400,  'What country is widely credited as the birthplace of croissants?',                     'France'),
  (400,  'What is the name of the Indian clay oven used for cooking flatbreads and meats?',      'Tandoor'),
  (400,  'What is the difference between espresso and regular brewed coffee?',                   'Espresso forces hot water under high pressure through finely-ground coffee; regular coffee uses slower brewing'),
  (400,  'What is sashimi?',                                                                      'Fresh raw fish sliced thinly and served without rice'),
  (400,  'What vegetable is primarily used to make traditional kimchi?',                         'Napa cabbage (baechu)'),
  (400,  'What type of pasta is shaped like long hollow tubes?',                                  'Penne (or rigatoni, ziti — any tubular pasta)'),
  (600,  'What expensive spice comes from the dried stigmas of Crocus sativus flowers?',         'Saffron'),
  (600,  'What French technique involves cooking vacuum-sealed food in a temperature-controlled water bath?', 'Sous vide'),
  (600,  'What is umami?',                                                                         'The fifth basic taste — often described as savoury or meaty'),
  (600,  'What country originated kimchi?',                                                       'South Korea'),
  (600,  'What is a tagine?',                                                                     'A Moroccan slow-cooked stew prepared in a conical clay pot of the same name'),
  (600,  'What is prosciutto?',                                                                   'Italian dry-cured ham sliced thinly and typically served uncooked'),
  (600,  'What makes sourdough bread different from regular bread?',                              'It is leavened by wild yeast and bacteria (a sourdough starter) rather than commercial yeast'),
  (600,  'What is blanching in cooking?',                                                         'Briefly boiling food then plunging it into ice water to stop cooking and preserve colour'),
  (800,  'What reaction between amino acids and sugars causes food to brown at high heat?',      'The Maillard reaction'),
  (800,  'What was the ancient Roman fish sauce used as a condiment?',                           'Garum'),
  (800,  'What is confit in cooking?',                                                            'Slow-cooking food submerged in its own fat at a low temperature (e.g., duck confit)'),
  (800,  'What is the difference between stock and broth?',                                      'Stock is made from bones (rich in gelatin); broth is made from meat'),
  (800,  'What region of Spain is paella from?',                                                  'Valencia'),
  (800,  'What is molecular gastronomy?',                                                         'A scientific approach applying chemistry and physics to create novel food textures and presentations'),
  (800,  'What is umeboshi?',                                                                     'Japanese pickled plums preserved in salt — intensely sour and salty'),
  (800,  'What is the Korean fermented chilli paste used widely in Korean cooking?',             'Gochujang'),
  (1000, 'What compound is responsible for the spicy heat in chilli peppers?',                   'Capsaicin'),
  (1000, 'What yeast strain is used in most wine and beer fermentation?',                        'Saccharomyces cerevisiae'),
  (1000, 'What is terroir in wine?',                                                              'The complete natural environment — soil, climate, topography — that shapes a wine''s unique character'),
  (1000, 'What is rendering in cooking?',                                                         'Slowly melting and extracting fat from meat or fat tissue over low heat'),
  (1000, 'What is the Scoville scale used for?',                                                  'Measuring the heat of chilli peppers and spicy foods by quantifying capsaicin concentration'),
  (1000, 'What is koji in Japanese food fermentation?',                                           'The mould Aspergillus oryzae, used to ferment miso, sake, soy sauce, and mirin'),
  (1000, 'What is Parmigiano-Reggiano and where must it be produced?',                           'Italian hard cheese aged at least 12 months, legally protected and produced only in Parma, Reggio Emilia, and surrounding areas'),
  (1000, 'What is mise en place?',                                                                'French culinary concept meaning "everything in its place" — preparing and organising ingredients before cooking'),
  (1200, 'What enzymatic reaction makes a cut apple turn brown?',                                'Oxidation (enzymatic browning) catalysed by polyphenol oxidase reacting with oxygen'),
  (1200, 'What is transglutaminase and how is it used in cooking?',                              'An enzyme ("meat glue") that bonds proteins together — used in modernist cuisine to combine proteins'),
  (1200, 'At approximately what temperature (Celsius) does the Maillard reaction occur?',        'Approximately 140–165°C (284–329°F)'),
  (1200, 'What is the difference between kefir and yogurt?',                                     'Kefir uses bacteria and yeast (kefir grains), producing a thinner, slightly fizzy drink; yogurt uses only bacteria'),
  (1200, 'What is escabeche?',                                                                    'A Mediterranean/Latin American technique of marinating cooked fish or meat in vinegar and spices'),
  (1200, 'How does acid make meat more tender when used in a marinade?',                         'Acid denaturation — it breaks down protein structures (collagen and muscle fibres), softening texture'),
  (1200, 'What is the French cooking term suer and what does it mean?',                          'To sweat — gently cooking aromatics in butter over low heat until soft without browning'),
  (1200, 'What is tataki in Japanese cooking?',                                                   'Lightly searing fish or meat on the outside while leaving it raw inside, then slicing thinly')
) AS q(pts, q_en, a_en)
WHERE c.name_en = 'Food & Drink';

-- 12. NATURE (50 questions)
INSERT INTO questions (category_id, points, question_en, answer_en, question_ar, answer_ar)
SELECT c.id, q.pts, q.q_en, q.a_en, '', ''
FROM categories c
CROSS JOIN (VALUES
  (200,  'What is the largest animal on Earth?',                                                  'The blue whale'),
  (200,  'What do caterpillars transform into?',                                                  'Butterflies (or moths)'),
  (200,  'How many legs does a spider have?',                                                     'Eight legs'),
  (200,  'What is the name of the cycle by which water evaporates, forms clouds, and falls as rain?', 'The water cycle (hydrological cycle)'),
  (200,  'What is the most abundant gas in Earth''s atmosphere?',                                  'Nitrogen (~78%)'),
  (200,  'What do we call an animal that eats only plants?',                                      'A herbivore'),
  (200,  'What is Earth''s natural satellite called?',                                             'The Moon'),
  (200,  'What is the largest land animal?',                                                      'The African elephant'),
  (200,  'What do we call animals that are active at night?',                                     'Nocturnal animals'),
  (400,  'How many bones does an adult human body have?',                                         '206 bones'),
  (400,  'What is the name of the largest species of shark?',                                    'The whale shark'),
  (400,  'How long does it take Earth to orbit the Sun?',                                        'Approximately 365.25 days (one year)'),
  (400,  'What colour is chlorophyll — the pigment that makes plants green?',                    'Green'),
  (400,  'What is the process by which a tadpole becomes a frog?',                               'Metamorphosis'),
  (400,  'What type of animal is a dolphin?',                                                     'A mammal'),
  (400,  'What percentage of Earth''s surface is covered by water?',                              'Approximately 71%'),
  (400,  'What is the study of living organisms called?',                                         'Biology'),
  (400,  'What is the layer of Earth between the crust and the core called?',                    'The mantle'),
  (600,  'What is the name of the deepest known point in the ocean?',                            'Challenger Deep (in the Mariana Trench)'),
  (600,  'What is the term for an animal that is active during twilight hours — dawn and dusk?', 'Crepuscular'),
  (600,  'What warm ocean current keeps Western Europe milder than similar latitudes?',           'The Gulf Stream (North Atlantic Current)'),
  (600,  'What is the difference between a stalactite and a stalagmite?',                        'Stalactites hang from the ceiling; stalagmites grow from the floor'),
  (600,  'What is a constellation?',                                                              'A group of stars forming a recognisable pattern, traditionally named after figures, animals, or objects'),
  (600,  'What is the term for an organism that breaks down dead organic matter?',               'A decomposer (or detritivore)'),
  (600,  'What is the name of the process by which water moves through a plant from roots to leaves?', 'Transpiration'),
  (600,  'What is the outer solid layer of Earth called?',                                        'The lithosphere (comprising the crust and upper mantle)'),
  (800,  'What is the scientific term for the process by which trees shed their leaves in autumn?', 'Abscission'),
  (800,  'What is a territory in animal behaviour?',                                              'A geographic area an animal defends against others, especially of its own species'),
  (800,  'What is El Niño?',                                                                      'A weather phenomenon where central and eastern Pacific Ocean temperatures become unusually warm'),
  (800,  'What type of rock forms from compressed layers of sediment over long periods?',        'Sedimentary rock'),
  (800,  'What is thermohaline circulation?',                                                     'Large-scale ocean circulation driven by temperature and salinity differences (the ocean conveyor belt)'),
  (800,  'What is the symbiotic relationship between a clownfish and a sea anemone classified as?', 'Mutualism — both species benefit'),
  (800,  'What is a keystone species?',                                                           'A species with a disproportionately large effect on its ecosystem relative to its abundance'),
  (800,  'How many neurons does the human brain contain approximately?',                          'About 86 billion neurons'),
  (1000, 'What is the Coriolis effect in weather systems?',                                       'The deflection of winds and ocean currents caused by Earth''s rotation — rightward in the Northern Hemisphere'),
  (1000, 'What is upwelling in oceanography?',                                                   'The phenomenon where cold, nutrient-rich water rises to the ocean surface'),
  (1000, 'What is the aphotic zone of the ocean?',                                               'The zone where sunlight does not penetrate (also called the midnight or bathypelagic zone)'),
  (1000, 'What is nitrogen fixation?',                                                            'Bacteria converting atmospheric nitrogen gas (N₂) into ammonia (NH₃) that plants can use'),
  (1000, 'What is homeostasis?',                                                                  'The biological process by which living organisms maintain stable internal conditions despite external changes'),
  (1000, 'What is natal philopatry?',                                                             'The tendency of animals to return to their exact birthplace to reproduce'),
  (1000, 'What three periods make up the Mesozoic Era?',                                          'Triassic, Jurassic, and Cretaceous'),
  (1000, 'What geological epoch do we currently live in?',                                        'The Holocene epoch (some argue we have entered the Anthropocene)'),
  (1200, 'What is the difference between mitosis and meiosis?',                                  'Mitosis produces two identical diploid cells; meiosis produces four diverse haploid cells for reproduction'),
  (1200, 'What enzyme breaks down hydrogen peroxide in cells to protect them from oxidative damage?', 'Catalase'),
  (1200, 'What is the imaginary line dividing Earth into Eastern and Western hemispheres?',      'The Prime Meridian (0° longitude)'),
  (1200, 'What is species richness in ecology?',                                                  'The number of different species present in a particular area — a key measure of biodiversity'),
  (1200, 'What is an extremophile?',                                                              'An organism that thrives in extreme environments such as very high/low temperatures, high salinity, or acidity'),
  (1200, 'What is the approximate depth of the ocean''s abyssal zone?',                          'Approximately 3–6 km (3,000–6,000 metres)'),
  (1200, 'What is terrestrialisation?',                                                           'The evolutionary process by which aquatic organisms colonised land, beginning around 375 million years ago'),
  (1200, 'What is biomagnification?',                                                             'The increasing concentration of toxic substances in tissues of organisms at each higher level of the food chain')
) AS q(pts, q_en, a_en)
WHERE c.name_en = 'Nature';

-- 13. POLITICS (50 questions)
INSERT INTO questions (category_id, points, question_en, answer_en, question_ar, answer_ar)
SELECT c.id, q.pts, q.q_en, q.a_en, '', ''
FROM categories c
CROSS JOIN (VALUES
  (200,  'How many permanent members does the UN Security Council have?',                         'Five permanent members'),
  (200,  'What does NATO stand for?',                                                             'North Atlantic Treaty Organization'),
  (200,  'What is a democracy?',                                                                  'A system of government where power belongs to the people, typically through elected representatives'),
  (200,  'What does OPEC stand for?',                                                             'Organization of the Petroleum Exporting Countries'),
  (200,  'What is the capital city of the United States?',                                        'Washington, D.C.'),
  (200,  'What is the governing document of the United States called?',                           'The Constitution'),
  (200,  'How many countries are members of the United Nations approximately?',                  '193 member states'),
  (200,  'What is the US legislative body that makes laws called?',                               'Congress (Senate and House of Representatives)'),
  (200,  'What is a dictatorship?',                                                               'A political system run by one person or group with absolute power'),
  (400,  'What political system divides power between central and regional governments?',         'Federalism'),
  (400,  'In what year was the Universal Declaration of Human Rights adopted by the UN?',        '1948'),
  (400,  'What building is where the US Congress meets?',                                         'The United States Capitol Building'),
  (400,  'What is the difference between a republic and a direct democracy?',                    'A republic uses elected representatives; a direct democracy has citizens vote directly on all laws'),
  (400,  'What is the UK legislative body called?',                                               'Parliament (House of Commons and House of Lords)'),
  (400,  'What is a formal agreement between two or more countries called?',                     'A treaty'),
  (400,  'Who was the first leader of the Soviet Union?',                                         'Vladimir Lenin'),
  (400,  'What is the judicial branch of government?',                                            'The branch that interprets laws and administers justice'),
  (400,  'What country has the world''s oldest Parliament (the Althing, founded 930 AD)?',       'Iceland'),
  (600,  'Who was the first Secretary-General of the United Nations?',                           'Trygve Lie (Norway)'),
  (600,  'What Latin term means past court decisions must be followed in similar future cases?',  'Stare decisis'),
  (600,  'What is proportional representation in electoral systems?',                             'A system where the percentage of legislative seats matches the percentage of votes a party receives'),
  (600,  'What is the difference between parliamentary and presidential government systems?',    'Parliamentary: the executive comes from the legislature; Presidential: the executive is separately elected'),
  (600,  'What is veto power in the UN Security Council?',                                        'The ability of any permanent member to block a resolution by voting against it'),
  (600,  'What is the founding treaty of the European Union?',                                   'The Treaty of Maastricht (1992)'),
  (600,  'What is gerrymandering?',                                                               'Manipulating electoral district boundaries to give one political party an unfair advantage'),
  (600,  'What political theory did Karl Marx develop?',                                          'Marxism (or scientific socialism / historical materialism)'),
  (800,  'What is the social contract theory in political philosophy?',                          'Individuals give up some freedoms to a governing authority in exchange for protection of their remaining rights'),
  (800,  'What is the Westphalian system in international relations?',                           'The system of sovereign nation-states recognising each other''s right to rule without external interference'),
  (800,  'What is the democratic peace theory?',                                                  'The observation that democratic countries rarely go to war with each other'),
  (800,  'What is soft power in international relations?',                                        'Influence achieved through attraction, culture, and values rather than military or economic coercion'),
  (800,  'What is habeas corpus?',                                                                'The legal right requiring someone arrested to be brought before a judge — protecting against unlawful detention'),
  (800,  'What is judicial review in the United States?',                                         'The power of the Supreme Court to declare laws unconstitutional — established by Marbury v. Madison (1803)'),
  (800,  'What is the UN Responsibility to Protect (R2P) doctrine?',                             'The principle that states must protect citizens from mass atrocities, and the international community may intervene if they fail'),
  (800,  'What is nationalism as a political doctrine?',                                          'The belief that people sharing a national identity should govern themselves in their own independent state'),
  (1000, 'What is the Overton Window in political science?',                                      'The range of policies the public currently considers acceptable — ideas outside it are seen as radical'),
  (1000, 'What is the prisoners'' dilemma and its relevance to politics?',                        'A game theory scenario where self-interest leads to worse outcomes for both parties than cooperation would — illustrating why international cooperation is difficult'),
  (1000, 'What is the difference between de jure and de facto sovereignty?',                     'De jure is legally recognised sovereignty; de facto is actual control regardless of legal recognition'),
  (1000, 'What is the realist school of thought in international relations?',                    'States act in self-interest in an anarchic system; power and security are the primary drivers of behaviour'),
  (1000, 'What is the Treaty on the Non-Proliferation of Nuclear Weapons (NPT)?',               'An international treaty preventing spread of nuclear weapons, promoting disarmament and peaceful nuclear use'),
  (1000, 'What is multilateralism in international relations?',                                   'The coordination of foreign policy among multiple countries, often through international institutions'),
  (1000, 'What is lobbying and why is it controversial?',                                         'Organised effort to influence government decisions; controversial because wealthy groups may gain disproportionate political power'),
  (1000, 'What is liberal institutionalism in international relations?',                          'The theory that international institutions and cooperation can overcome anarchy and promote peace'),
  (1200, 'What is Arrow''s Impossibility Theorem?',                                               'No ranked voting system can simultaneously satisfy all "fair" criteria when there are three or more candidates'),
  (1200, 'What is the difference between deontological and consequentialist ethics?',            'Deontological ethics judges by adherence to rules/duties; consequentialist ethics judges by outcomes'),
  (1200, 'What is the Gini coefficient used to measure?',                                         'Income or wealth inequality — 0 is perfect equality, 1 (or 100%) is maximum inequality'),
  (1200, 'What is subsidiarity in EU law?',                                                       'Decisions should be made at the most local level possible; higher levels intervene only when necessary'),
  (1200, 'What are Max Weber''s three types of political authority?',                              'Traditional (custom), charismatic (personal qualities), and rational-legal (rules and laws)'),
  (1200, 'What is popular sovereignty?',                                                          'The principle that government authority is derived from and legitimised by the consent of the governed'),
  (1200, 'What are the three pillars of the UN Responsibility to Protect doctrine?',              '1) State responsibility; 2) International assistance; 3) International intervention when states manifestly fail'),
  (1200, 'Who wrote A Theory of Justice (1971), reviving liberal political philosophy?',          'John Rawls')
) AS q(pts, q_en, a_en)
WHERE c.name_en = 'Politics';

-- Done! Run a quick sanity check:
SELECT c.name_en, COUNT(q.id) as question_count
FROM categories c
LEFT JOIN questions q ON q.category_id = c.id
GROUP BY c.name_en
ORDER BY c.name_en;
